const icons = [
  {
    id: 'persobrand',
    name: 'Personal',
    icons: [
      { key: "icon-aerosafety", icon: "icon-aerosafety", name: "Aerosafety", color: '#4285F4' },
      { key: "icon-air-data", icon: "icon-air-data", name: "Air Data", color: '#FF4500' },
      { key: "icon-bc", icon: "icon-bc", name: "BC", color: null },
      { key: "icon-bmw", icon: "icon-bmw", name: "BMW", color: '#0093DD' },
      { key: "icon-brusselsaquariums", icon: "icon-brusselsaquariums", name: "Brussels Aquariums", color: '#00B5AC' },
      { key: "icon-cityzendesk", icon: "icon-cityzendesk", name: "CityZenDesk", color: '#3BBCD8' },
      { key: "icon-cityzendesk-alt", icon: "icon-cityzendesk-alt", name: "CityZenDesk", color: '#3BBCD8' },
      { key: "icon-crazytips", icon: "icon-crazytips", name: "Crazy Tips", color: null },
      { key: "icon-crazytips-alt", icon: "icon-crazytips-alt", name: "Crazy Tips", color: null },
      { key: "icon-crypto-viewer", icon: "icon-crypto-viewer", name: "Crypto Viewer", color: '#1543E4' },
      { key: "icon-ctw", icon: "icon-ctw", name: "CTW", color: null },
      { key: "icon-ctw-alt", icon: "icon-ctw-alt", name: "CTW", color: null },
      { key: "icon-cvbroker", icon: "icon-cvbroker", name: "CV-Broker", color: '#4285F4' },
      { key: "icon-dict", icon: "icon-dict", name: "Dict", color: null },
      { key: "icon-dict-alt", icon: "icon-dict-alt", name: "Dict", color: null },
      { key: "icon-dolcegusto", icon: "icon-dolcegusto", name: "Dolce Gusto", color: null },
      { key: "icon-dolcegusto-alt", icon: "icon-dolcegusto-alt", name: "Dolce Gusto", color: null },
      { key: "icon-dolcegusto-alt2", icon: "icon-dolcegusto-alt2", name: "Dolce Gusto", color: null },
      { key: "icon-eco2mix", icon: "icon-eco2mix", name: "Eco2mix", color: null },
      { key: "icon-enos", icon: "icon-enos", name: "E-nos", color: '#43A047' },
      { key: "icon-enos-alt", icon: "icon-enos-alt", name: "E-nos", color: '#43A047' },
      { key: "icon-evento", icon: "icon-evento", name: "Evento", color: '#E91E63' },
      { key: "icon-evento-alt", icon: "icon-evento-alt", name: "Evento", color: '#E91E63' },
      { key: "icon-evento-alt2", icon: "icon-evento-alt2", name: "Evento", color: '#E91E63' },
      { key: "icon-expositions", icon: "icon-expositions", name: "Expositions", color: null },
      { key: "icon-factorio", icon: "icon-factorio", name: "Factorio", color: '#304FFE' },
      { key: "icon-findanumbrella", icon: "icon-findanumbrella", name: "FindAnUmbrella", color: '#FFD469' },
      { key: "icon-geosnap", icon: "icon-geosnap", name: "Geosnap", color: '#FDC300' },
      { key: "icon-geosnap-alt", icon: "icon-geosnap-alt", name: "Geosnap", color: '#FDC300' },
      { key: "icon-ideomed", icon: "icon-ideomed", name: "IdeoMed", color: null },
      { key: "icon-jsonimate", icon: "icon-jsonimate", name: "Jsonimate", color: null },
      { key: "icon-jsonimate-alt", icon: "icon-jsonimate-alt", name: "Jsonimate", color: null },
      { key: "icon-launchpad", icon: "icon-launchpad", name: "Launchpad", color: null },
      { key: "icon-logistics", icon: "icon-logistics", name: "Logistics", color: '#113885' },
      { key: "icon-logistics-alt", icon: "icon-logistics-alt", name: "Logistics", color: '#113885' },
      { key: "icon-maplink", icon: "icon-maplink", name: "Maplink", color: '#FDC300' },
      { key: "icon-maplink-alt", icon: "icon-maplink-alt", name: "Maplink", color: '#FDC300' },
      { key: "icon-maplink-alt2", icon: "icon-maplink-alt2", name: "Maplink", color: '#FDC300' },
      { key: "icon-mujsic", icon: "icon-mujsic", name: "icon-mujsic", color: null },
      { key: "icon-myachievements", icon: "icon-myachievements", name: "My Achievements", color: '#33B5E5' },
      { key: "icon-mylandlordclub", icon: "icon-mylandlordclub", name: "MyLandlordClub", color: null },
      { key: "icon-optidis", icon: "icon-optidis", name: "Optidis", color: '#2BBBAD' },
      { key: "icon-optidis-alt", icon: "icon-optidis-alt", name: "Optidis", color: '#2BBBAD' },
      { key: "icon-optidis-alt2", icon: "icon-optidis-alt2", name: "Optidis", color: '#2BBBAD' },
      { key: "icon-pdt", icon: "icon-pdt", name: "PDT", color: null },
      { key: "icon-rjo", icon: "icon-rjo", name: "RJO", color: null },
      { key: "icon-rjo-alt", icon: "icon-rjo-alt", name: "RJO", color: null },
      { key: "icon-skillmatrix", icon: "icon-skillmatrix", name: "SkillMatrix", color: '#DD7627' },
      { key: "icon-skillmatrix-alt", icon: "icon-skillmatrix-alt", name: "SkillMatrix", color: '#DD7627' },
      { key: "icon-studies", icon: "icon-studies", name: "Studies", color: '#00A6D9' },
      { key: "icon-travels", icon: "icon-travels", name: "Travels", color: null },
      { key: "icon-vemasys", icon: "icon-vemasys", name: "Vemasys", color: '#DD7627' },
      { key: "icon-vemasys-alt", icon: "icon-vemasys-alt", name: "Vemasys", color: '#DD7627' },
      { key: "icon-ain", icon: "icon-ain", name: "Ain", color: '#123C5E' },
      { key: "icon-braytonglobal", icon: "icon-braytonglobal", name: "Brayton Global", color: '#DD7627' },
      { key: "icon-braytonglobal-alt", icon: "icon-braytonglobal-alt", name: "Brayton Global", color: '#DD7627' },
      { key: "icon-cci", icon: "icon-cci", name: "CCI", color: null },
      { key: "icon-citylity", icon: "icon-citylity", name: "Citylity", color: '#3BBCD8' },
      { key: "icon-cnh", icon: "icon-cnh", name: "CNH", color: '#A32428' },
      { key: "icon-cnhindustrial", icon: "icon-cnhindustrial", name: "CNH Industrial", color: '#A32428' },
      { key: "icon-harvard", icon: "icon-harvard", name: "Harvard", color: '#A31F32' },
      { key: "icon-harvard-alt", icon: "icon-harvard-alt", name: "Harvard", color: '#A31F32' },
      { key: "icon-harvardx-alt", icon: "icon-harvardx-alt", name: "HarvardX", color: '#A31F32' },
      { key: "icon-intitek", icon: "icon-intitek", name: "Intitek", color: '#E84E0F' },
      { key: "icon-iunex", icon: "icon-iunex", name: "Iunex Group", color: '#A6BABA' },
      { key: "icon-iunex-alt", icon: "icon-iunex-alt", name: "Iunex Group", color: '#A6BABA' },
      { key: "icon-lyceesjeanmonnet", icon: "icon-lyceesjeanmonnet", name: "LJM", color: '#155C70' },
      { key: "icon-lyon1", icon: "icon-lyon1", name: "Lyon1", color: null },
      { key: "icon-maincare", icon: "icon-maincare", name: "Maincare", color: '#E34624' },
      { key: "icon-maincare-alt", icon: "icon-maincare-alt", name: "Maincare", color: '#E34624' },
      { key: "icon-polyenco", icon: "icon-polyenco", name: "Polyenco", color: null },
      { key: "icon-polytech", icon: "icon-polytech", name: "Polytech", color: '#009DDE' },
      { key: "icon-polytech-alt", icon: "icon-polytech-alt", name: "Polytech", color: '#009DDE' },
      { key: "icon-sogelink", icon: "icon-sogelink", name: "Sogelink", color: '#FDC300' },
      { key: "icon-sogelink-alt", icon: "icon-sogelink-alt", name: "Sogelink", color: '#FDC300' },
      { key: "icon-sogelink-alt2", icon: "icon-sogelink-alt2", name: "Sogelink", color: '#FDC300' },
      { key: "icon-tc-gannay", icon: "icon-tc-gannay", name: "TC Gannay", color: '#FF1D1D' },
      { key: "icon-tc-gannay-alt", icon: "icon-tc-gannay-alt", name: "TC Gannay", color: '#FF1D1D' },
      { key: "icon-universitelyon", icon: "icon-universitelyon", name: "Universite Lyon", color: null },
      { key: "icon-vdsconsulting", icon: "icon-vdsconsulting", name: "VDS Consulting", color: '#FFD469' },
      { key: "icon-vdsconsulting-alt", icon: "icon-vdsconsulting-alt", name: "VDS Consulting", color: '#FFD469' },
      { key: "icon-vdsconsulting-alt2", icon: "icon-vdsconsulting-alt2", name: "VDS Consulting", color: '#FFD469' },
      { key: "icon-velov", icon: "icon-velov", name: "Velov", color: '#FF0000' },
      { key: "icon-velov-alt", icon: "icon-velov-alt", name: "Velov", color: '#FF0000' },
      { key: "icon-velov-alt2", icon: "icon-velov-alt2", name: "Velov", color: '#FF0000' },
    ],
    hidden: true
  },
  {
    id: 'os',
    name: 'Operating Systems',
    icons: [
      { key: "icon-archlinux", icon: "icon-archlinux", name: "Arch Linux", color: '#1793D1' },
      { key: "icon-archlinux-alt", icon: "icon-archlinux-alt", name: "Arch Linux", color: '#1793D1' },
      { key: "icon-bootcamp", icon: "icon-bootcamp", name: "Bootcamp", color: '#787878' },
      { key: "icon-centos", icon: "icon-centos", name: "CentOS", color: '#252476' },
      { key: "icon-debian", icon: "icon-debian", name: "Debian", color: '#D70751' },
      { key: "icon-fedora", icon: "icon-fedora", name: "Fedora", color: '#294172' },
      { key: "icon-fedora-alt", icon: "icon-fedora-alt", name: "Fedora", color: '#294172' },
      { key: "icon-gnome", icon: "icon-gnome", name: "Gnome", color: null },
      { key: "icon-kubuntu", icon: "icon-kubuntu", name: "KUbuntu", color: '#0079C1' },
      { key: "icon-kubuntu-alt", icon: "icon-kubuntu-alt", name: "KUbuntu", color: '#0079C1' },
      { key: "icon-linux-mint", icon: "icon-linux-mint", name: "Linux Mint", color: '#88D040' },
      { key: "icon-mac-os", icon: "icon-mac-os", name: "MacOS", color: null },
      { key: "icon-mac-os-alt", icon: "icon-mac-os-alt", name: "MacOS", color: null },
      { key: "icon-solaris", icon: "icon-solaris", name: "Solaris", color: '#EB882B' },
      { key: "icon-ubuntu", icon: "icon-ubuntu", name: "Ubuntu", color: '#DD4814' },
      { key: "icon-unix", icon: "icon-unix", name: "Unix", color: null },
      { key: "icon-windows", icon: "icon-windows", name: "Windows", color: '#3A96DD' },
      { key: "icon-windows7", icon: "icon-windows7", name: "Windows 7", color: '#167CB5' },
      { key: "icon-windows8", icon: "icon-windows8", name: "Windows 8", color: '#3A96DD' },
      { key: "icon-windows10", icon: "icon-windows10", name: "Windows 10", color: '#3A96DD' },
    ]
  },
  {
    id: 'brand',
    name: 'Brands',
    icons: [
      { key: "icon-adobe", icon: "icon-adobe", name: "Adobe", color: '#FF0000' },
      { key: "icon-apple", icon: "icon-apple", name: "Apple", color: '#666666' },
      { key: "icon-bing", icon: "icon-bing", name: "Bing", color: '#008272' },
      { key: "icon-bing-alt", icon: "icon-bing-alt", name: "Bing", color: '#008272' },
      { key: "icon-bitnami", icon: "icon-bitnami", name: "Bitnami", color: '#00437B' },
      { key: "icon-cisco", icon: "icon-cisco", name: "Cisco", color: '#C22433' },
      { key: "icon-citrix", icon: "icon-citrix", name: "Citrix", color: '#231F20' },
      { key: "icon-digitalocean", icon: "icon-digitalocean", name: "Digital Ocean", color: '#0069FF' },
      { key: "icon-duckduckgo", icon: "icon-duckduckgo", name: "DuckDuckGo", color: '#DE5833' },
      { key: "icon-fireeye", icon: "icon-fireeye", name: "FireEye", color: '#CC1B26' },
      { key: "icon-google", icon: "icon-google", name: "Google", color: '#4081ED' },
      { key: "icon-hashicorp", icon: "icon-hashicorp", name: "Hashicorp", color: null },
      { key: "icon-ibm", icon: "icon-ibm", name: "IBM", color: '#176EC0' },
      { key: "icon-ign", icon: "icon-ign", name: "IGN", color: null },
      { key: "icon-itext", icon: "icon-itext", name: "Itext", color: '#F99D25' },
      { key: "icon-jetbrains", icon: "icon-jetbrains", name: "JetBrains", color: '#E74A72' },
      { key: "icon-jetbrains-alt", icon: "icon-jetbrains-alt", name: "JetBrains", color: '#E74A72' },
      { key: "icon-kde", icon: "icon-kde", name: "KDE", color: '#31363B' },
      { key: "icon-logrhythm", icon: "icon-logrhythm", name: "Logrhythm", color: '#2B72B9' },
      { key: "icon-logrhythm-alt", icon: "icon-logrhythm-alt", name: "Logrhythm", color: '#2B72B9' },
      { key: "icon-microsoft", icon: "icon-microsoft", name: "Microsoft", color: null },
      { key: "icon-oracle", icon: "icon-oracle", name: "Oracle", color: '#E32124' },
      { key: "icon-oracle-alt", icon: "icon-oracle-alt", name: "Oracle", color: '#E32124' },
      { key: "icon-ovh", icon: "icon-ovh", name: "OVH", color: '#15406B' },
      { key: "icon-qlik", icon: "icon-qlik", name: "Qlik", color: '#63A330' },
      { key: "icon-qualys", icon: "icon-qualys", name: "Qualys", color: '#ED2E26' },
      { key: "icon-qwant", icon: "icon-qwant", name: "Qwant", color: null },
      { key: "icon-redhat", icon: "icon-redhat", name: "Red Hat", color: '#EE0000' },
      { key: "icon-servicenow", icon: "icon-servicenow", name: "ServiceNow", color: '#7AB09C' },
      { key: "icon-vmware", icon: "icon-vmware", name: "VM Ware", color: '#00668C' },
      { key: "icon-w3c", icon: "icon-w3c", name: "W3C", color: '#004894' },
      { key: "icon-yahoo", icon: "icon-yahoo", name: "Yahoo", color: '#6001D2' },
      { key: "icon-yahoo-alt", icon: "icon-yahoo-alt", name: "Yahoo", color: '#6001D2' },
      { key: "icon-yahoo-alt2", icon: "icon-yahoo-alt2", name: "Yahoo", color: '#6001D2' },
    ]
  },
  {
    id: 'cloud',
    name: 'Cloud & Virtualization',
    icons: [
      { key: "icon-aws", icon: "icon-aws", name: "AWS", color: '#FF9900' },
      { key: "icon-azure", icon: "icon-azure", name: "Azure", color: '#2075B8' },
      { key: "icon-azure-alt", icon: "icon-azure-alt", name: "Azure", color: '#2075B8' },
      { key: "icon-cloudera", icon: "icon-cloudera", name: "Cloudera", color: '#F95800' },
      { key: "icon-cozycloud", icon: "icon-cozycloud", name: "Cozycloud", color: '#297EF2' },
      { key: "icon-cozycloud-alt", icon: "icon-cozycloud-alt", name: "Cozycloud", color: '#297EF2' },
      { key: "icon-creativecloud", icon: "icon-creativecloud", name: "Creative Cloud", color: '#DA1F26' },
      { key: "icon-docker", icon: "icon-docker", name: "Docker", color: '#2496ED' },
      { key: "icon-filezilla", icon: "icon-filezilla", name: "FileZilla", color: '#B30000' },
      { key: "icon-google-cloud", icon: "icon-google-cloud", name: "Google Cloud", color: '#4285F4' },
      { key: "icon-heroku", icon: "icon-heroku", name: "Heroku", color: '#430098' },
      { key: "icon-openshift", icon: "icon-openshift", name: "OpenShift", color: '#DB212E' },
      { key: "icon-openstack", icon: "icon-openstack", name: "OpenStack", color: '#F3163F' },
      { key: "icon-parallels", icon: "icon-parallels", name: "Parallels", color: '#D80018' },
      { key: "icon-qemu", icon: "icon-qemu", name: "Qemu", color: '#FF6501' },
      { key: "icon-qemu-alt", icon: "icon-qemu-alt", name: "Qemu", color: '#FF6501' },
      { key: "icon-saltstack", icon: "icon-saltstack", name: "SaltStack", color: null },
      { key: "icon-scaleway", icon: "icon-scaleway", name: "Scaleway", color: '#510098' },
      { key: "icon-vagrant", icon: "icon-vagrant", name: "Vagrant", color: '#127EFF' },
      { key: "icon-vagrant-alt", icon: "icon-vagrant-alt", name: "Vagrant", color: '#127EFF' },
      { key: "icon-vmware-fusion", icon: "icon-vmware-fusion", name: "VM Ware Fusion", color: '#1D72CC' },
      { key: "icon-vmware-player", icon: "icon-vmware-player", name: "VM Ware Player", color: '#FFCE23' },
      { key: "icon-vmware-workstation", icon: "icon-vmware-workstation", name: "VM Ware Workstation", color: '#F48500' },
      { key: "icon-vnc", icon: "icon-vnc", name: "VNC", color: '#FF0707' },
      { key: "icon-winscp", icon: "icon-winscp", name: "WinSCP", color: '#2D91DF' },
      { key: "icon-aws-artifact", icon: "icon-aws-artifact", name: "aws-artifact", color: null },
      { key: "icon-aws-certificatemanager", icon: "icon-aws-certificatemanager", name: "aws-certificatemanager", color: null },
      { key: "icon-aws-cloudhsm", icon: "icon-aws-cloudhsm", name: "aws-cloudhsm", color: null },
      { key: "icon-aws-cloudformation", icon: "icon-aws-cloudformation", name: "aws-cloudformation", color: null },
      { key: "icon-aws-cloudwatch", icon: "icon-aws-cloudwatch", name: "aws-cloudwatch", color: null },
      { key: "icon-aws-cloudtrail", icon: "icon-aws-cloudtrail", name: "aws-cloudtrail", color: null },
      { key: "icon-aws-cloudsearch", icon: "icon-aws-cloudsearch", name: "aws-cloudsearch", color: null },
      { key: "icon-aws-codecommit", icon: "icon-aws-codecommit", name: "aws-codecommit", color: null },
      { key: "icon-aws-agent", icon: "icon-aws-agent", name: "aws-agent", color: null },
      { key: "icon-aws-decider", icon: "icon-aws-decider", name: "aws-decider", color: null },
      { key: "icon-aws-config", icon: "icon-aws-config", name: "aws-config", color: null },
      { key: "icon-aws-dynamodb", icon: "icon-aws-dynamodb", name: "aws-dynamodb", color: null },
      { key: "icon-aws-codedeploy", icon: "icon-aws-codedeploy", name: "aws-codedeploy", color: null },
      { key: "icon-aws-directconnect", icon: "icon-aws-directconnect", name: "aws-directconnect", color: null },
      { key: "icon-aws-directoryservice", icon: "icon-aws-directoryservice", name: "aws-directoryservice", color: null },
      { key: "icon-aws-configlog", icon: "icon-aws-configlog", name: "aws-configlog", color: null },
      { key: "icon-aws-ec2", icon: "icon-aws-ec2", name: "aws-ec2", color: null },
      { key: "icon-aws-elasticbeanstalk", icon: "icon-aws-elasticbeanstalk", name: "aws-elasticbeanstalk", color: null },
      { key: "icon-aws-elasticache", icon: "icon-aws-elasticache", name: "aws-elasticache", color: null },
      { key: "icon-aws-apigateway", icon: "icon-aws-apigateway", name: "aws-apigateway", color: null },
      { key: "icon-aws-emr", icon: "icon-aws-emr", name: "aws-emr", color: null },
      { key: "icon-aws-glacier", icon: "icon-aws-glacier", name: "aws-glacier", color: null },
      { key: "icon-aws-elb", icon: "icon-aws-elb", name: "aws-elb", color: null },
      { key: "icon-aws-iam", icon: "icon-aws-iam", name: "aws-iam", color: null },
      { key: "icon-aws-kms", icon: "icon-aws-kms", name: "aws-kms", color: null },
      { key: "icon-asp", icon: "icon-asp", name: "asp", color: null },
      { key: "icon-aws-lambda", icon: "icon-aws-lambda", name: "icon-aws-lambda", color: null },
      { key: "icon-aws-ecs", icon: "icon-aws-ecs", name: "aws-ecs", color: null },
      { key: "icon-aws-kcl", icon: "icon-aws-kcl", name: "aws-kcl", color: null },
      { key: "icon-aws-marketplace", icon: "icon-aws-marketplace", name: "aws-marketplace", color: null },
      { key: "icon-aws-message", icon: "icon-aws-message", name: "aws-message", color: null },
      { key: "icon-aws-ebs", icon: "icon-aws-ebs", name: "aws-ebs", color: null },
      { key: "icon-aws-rds", icon: "icon-aws-rds", name: "aws-rds", color: null },
      { key: "icon-aws-elastictranscoder", icon: "icon-aws-elastictranscoder", name: "aws-elastictranscoder", color: null },
      { key: "icon-aws-route53", icon: "icon-aws-route53", name: "aws-route53", color: null },
      { key: "icon-aws-redshift", icon: "icon-aws-redshift", name: "aws-redshift", color: null },
      { key: "icon-aws-ses", icon: "icon-aws-ses", name: "aws-ses", color: null },
      { key: "icon-aws-networking", icon: "icon-aws-networking", name: "aws-networking", color: null },
      { key: "icon-aws-lambda-alt", icon: "icon-aws-lambda-alt", name: "aws-lambda-alt", color: null },
      { key: "icon-aws-sqs", icon: "icon-aws-sqs", name: "aws-sqs", color: null },
      { key: "icon-aws-swf", icon: "icon-aws-swf", name: "aws-swf", color: null },
      { key: "icon-aws-storagegateway", icon: "icon-aws-storagegateway", name: "aws-storagegateway", color: null },
      { key: "icon-aws-s3bucket", icon: "icon-aws-s3bucket", name: "aws-s3bucket", color: null },
      { key: "icon-aws-sns", icon: "icon-aws-sns", name: "aws-sns", color: null },
      { key: "icon-aws-organisations", icon: "icon-aws-organisations", name: "aws-organisations", color: null },
      { key: "icon-aws-waf", icon: "icon-aws-waf", name: "aws-waf", color: null },
      { key: "icon-aws-appstream", icon: "icon-aws-appstream", name: "aws-appstream", color: null },
      { key: "icon-aws-shield", icon: "icon-aws-shield", name: "aws-shield", color: null },
      { key: "icon-aws-vpn", icon: "icon-aws-vpn", name: "aws-vpn", color: null },
      { key: "icon-aws-vpc", icon: "icon-aws-vpc", name: "aws-vpc", color: null },
      { key: "icon-aws-worker", icon: "icon-aws-worker", name: "aws-worker", color: null },
      { key: "icon-aws-queue", icon: "icon-aws-queue", name: "aws-queue", color: null },
      { key: "icon-azure-activedirectory", icon: "icon-azure-activedirectory", name: "azure-activedirectory", color: null },
      { key: "icon-azure-accesscontrol", icon: "icon-azure-accesscontrol", name: "azure-accesscontrol", color: null },
      { key: "icon-azure-alert", icon: "icon-azure-alert", name: "azure-alert", color: null },
      { key: "icon-azure-applicationinsight", icon: "icon-azure-applicationinsight", name: "azure-applicationinsight", color: null },
      { key: "icon-azure-apimanagement", icon: "icon-azure-apimanagement", name: "azure-apimanagement", color: null },
      { key: "icon-azure-automation", icon: "icon-azure-automation", name: "azure-automation", color: null },
      { key: "icon-azure-apiapp", icon: "icon-azure-apiapp", name: "azure-apiapp", color: null },
      { key: "icon-azure-autoscaling", icon: "icon-azure-autoscaling", name: "azure-autoscaling", color: null },
      { key: "icon-azure-appservice", icon: "icon-azure-appservice", name: "azure-appservice", color: null },
      { key: "icon-azure-batch", icon: "icon-azure-batch", name: "azure-batch", color: null },
      { key: "icon-azure-cloudservice", icon: "icon-azure-cloudservice", name: "azure-cloudservice", color: null },
      { key: "icon-azure-backupservice", icon: "icon-azure-backupservice", name: "azure-backupservice", color: null },
      { key: "icon-azure-contentdeliverynetwork", icon: "icon-azure-contentdeliverynetwork", name: "azure-contentdeliverynetwork", color: null },
      { key: "icon-azure-cache", icon: "icon-azure-cache", name: "azure-cache", color: null },
      { key: "icon-azure-codeplex", icon: "icon-azure-codeplex", name: "azure-codeplex", color: null },
      { key: "icon-azure-biztalkservice", icon: "icon-azure-biztalkservice", name: "azure-biztalkservice", color: null },
      { key: "icon-azure-endpoint", icon: "icon-azure-endpoint", name: "azure-endpoint", color: null },
      { key: "icon-azure-eventhub", icon: "icon-azure-eventhub", name: "azure-eventhub", color: null },
      { key: "icon-azure-datafactory", icon: "icon-azure-datafactory", name: "azure-datafactory", color: null },
      { key: "icon-azure-expressroute", icon: "icon-azure-expressroute", name: "azure-expressroute", color: null },
      { key: "icon-azure-documentdb", icon: "icon-azure-documentdb", name: "azure-documentdb", color: null },
      { key: "icon-azure-filesservice", icon: "icon-azure-filesservice", name: "azure-filesservice", color: null },
      { key: "icon-azure-hybridconnection", icon: "icon-azure-hybridconnection", name: "azure-hybridconnection", color: null },
      { key: "icon-azure-keyvault", icon: "icon-azure-keyvault", name: "azure-keyvault", color: null },
      { key: "icon-azure-loadbalancer", icon: "icon-azure-loadbalancer", name: "azure-loadbalancer", color: null },
      { key: "icon-azure-logicapp", icon: "icon-azure-logicapp", name: "azure-logicapp", color: null },
      { key: "icon-azure-machinelearning", icon: "icon-azure-machinelearning", name: "azure-machinelearning", color: null },
      { key: "icon-azure-marketplace", icon: "icon-azure-marketplace", name: "azure-marketplace", color: null },
      { key: "icon-azure-mediaservice", icon: "icon-azure-mediaservice", name: "azure-mediaservice", color: null },
      { key: "icon-azure-microsoftaccount", icon: "icon-azure-microsoftaccount", name: "azure-microsoftaccount", color: null },
      { key: "icon-azure-mobileapp", icon: "icon-azure-mobileapp", name: "azure-mobileapp", color: null },
      { key: "icon-azure-mobileengagement", icon: "icon-azure-mobileengagement", name: "azure-mobileengagement", color: null },
      { key: "icon-azure-multifactorauthentication", icon: "icon-azure-multifactorauthentication", name: "azure-multifactorauthentication", color: null },
      { key: "icon-azure-mysqldatabase", icon: "icon-azure-mysqldatabase", name: "azure-mysqldatabase", color: null },
      { key: "icon-azure-notificationhubs", icon: "icon-azure-notificationhubs", name: "azure-notificationhubs", color: null },
      { key: "icon-azure-notificationtopic", icon: "icon-azure-notificationtopic", name: "azure-notificationtopic", color: null },
      { key: "icon-azure-office", icon: "icon-azure-office", name: "icon-azure-office", color: null },
      { key: "icon-azure-operationalinsights", icon: "icon-azure-operationalinsights", name: "azure-operationalinsights", color: null },
      { key: "icon-azure-osimage", icon: "icon-azure-osimage", name: "azure-osimage", color: null },
      { key: "icon-azure-remoteapp", icon: "icon-azure-remoteapp", name: "azure-remoteapp", color: null },
      { key: "icon-azure-remotingfile", icon: "icon-azure-remotingfile", name: "azure-remotingfile", color: null },
      { key: "icon-azure-rightsmanagement", icon: "icon-azure-rightsmanagement", name: "azure-rightsmanagement", color: null },
      { key: "icon-azure-scheduler", icon: "icon-azure-scheduler", name: "azure-scheduler", color: null },
      { key: "icon-azure-sdk", icon: "icon-azure-sdk", name: "azure-sdk", color: null },
      { key: "icon-azure-search", icon: "icon-azure-search", name: "azure-search", color: null },
      { key: "icon-azure-servicebus", icon: "icon-azure-servicebus", name: "azure-servicebus", color: null },
      { key: "icon-azure-servicebusqueue", icon: "icon-azure-servicebusqueue", name: "azure-servicebusqueue", color: null },
      { key: "icon-azure-servicebusrelay", icon: "icon-azure-servicebusrelay", name: "azure-servicebusrelay", color: null },
      { key: "icon-azure-servicebustopic", icon: "icon-azure-servicebustopic", name: "azure-servicebustopic", color: null },
      { key: "icon-azure-servicepackage", icon: "icon-azure-servicepackage", name: "azure-servicepackage", color: null },
      { key: "icon-azure-siterecovery", icon: "icon-azure-siterecovery", name: "azure-siterecovery", color: null },
      { key: "icon-azure-sqldatabase", icon: "icon-azure-sqldatabase", name: "azure-sqldatabase", color: null },
      { key: "icon-azure-sqldatabase-alt", icon: "icon-azure-sqldatabase-alt", name: "azure-sqldatabase-alt", color: null },
      { key: "icon-azure-sqldatasync", icon: "icon-azure-sqldatasync", name: "azure-sqldatasync", color: null },
      { key: "icon-azure-startuptask", icon: "icon-azure-startuptask", name: "azure-startuptask", color: null },
      { key: "icon-azure-storage", icon: "icon-azure-storage", name: "azure-storage", color: null },
      { key: "icon-azure-storageblob", icon: "icon-azure-storageblob", name: "azure-storageblob", color: null },
      { key: "icon-azure-storagetable", icon: "icon-azure-storagetable", name: "azure-storagetable", color: null },
      { key: "icon-azure-storsimple", icon: "icon-azure-storsimple", name: "azure-storsimple", color: null },
      { key: "icon-azure-streamanalytics", icon: "icon-azure-streamanalytics", name: "azure-streamanalytics", color: null },
      { key: "icon-azure-subscription", icon: "icon-azure-subscription", name: "azure-subscription", color: null },
      { key: "icon-azure-trafficmanager", icon: "icon-azure-trafficmanager", name: "azure-trafficmanager", color: null },
      { key: "icon-azure-vhd", icon: "icon-azure-vhd", name: "azure-vhd", color: null },
      { key: "icon-azure-vhddatadisk", icon: "icon-azure-vhddatadisk", name: "azure-vhddatadisk", color: null },
      { key: "icon-azure-virtualmachine", icon: "icon-azure-virtualmachine", name: "azure-virtualmachine", color: null },
      { key: "icon-azure-virtualnetwork", icon: "icon-azure-virtualnetwork", name: "azure-virtualnetwork", color: null },
      { key: "icon-azure-webapp", icon: "icon-azure-webapp", name: "azure-webapp", color: null },
      { key: "icon-azure-webjobs", icon: "icon-azure-webjobs", name: "azure-webjobs", color: null },
      { key: "icon-azure-webroles", icon: "icon-azure-webroles", name: "azure-webroles", color: null },
      { key: "icon-azure-workaccount", icon: "icon-azure-workaccount", name: "azure-workaccount", color: null },
      { key: "icon-azure-workerroles", icon: "icon-azure-workerroles", name: "azure-workerroles", color: null },
      { key: "icon-gcp-appengine", icon: "icon-gcp-appengine", name: "gcp-appengine", color: null },
      { key: "icon-gcp-appengine-alt", icon: "icon-gcp-appengine-alt", name: "gcp-appengine-alt", color: null },
      { key: "icon-gcp-bigquery", icon: "icon-gcp-bigquery", name: "gcp-bigquery", color: null },
      { key: "icon-gcp-bigquery-alt", icon: "icon-gcp-bigquery-alt", name: "gcp-bigquery-alt", color: null },
      { key: "icon-gcp-bigtable", icon: "icon-gcp-bigtable", name: "gcp-bigtable", color: null },
      { key: "icon-gcp-bigtable-alt", icon: "icon-gcp-bigtable-alt", name: "gcp-bigtable-alt", color: null },
      { key: "icon-gcp-container", icon: "icon-gcp-container", name: "gcp-container", color: null },
      { key: "icon-gcp-container-alt", icon: "icon-gcp-container-alt", name: "gcp-container-alt", color: null },
      { key: "icon-gcp-spanner", icon: "icon-gcp-spanner", name: "gcp-spanner", color: null },
      { key: "icon-gcp-spanner-alt", icon: "icon-gcp-spanner-alt", name: "gcp-spanner-alt", color: null },
    ]
  },
  {
    id: 'idedb',
    name: 'IDE & DB Softwares',
    icons: [
      { key: "icon-android-studio", icon: "icon-android-studio", name: "Android Studio", color: '#9FC24E' },
      { key: "icon-appcode", icon: "icon-appcode", name: "AppCode", color: '#12ACEC' },
      { key: "icon-appcode-alt", icon: "icon-appcode-alt", name: "AppCode", color: '#12ACEC' },
      { key: "icon-atom", icon: "icon-atom", name: "Atom", color: '#5BBD82' },
      { key: "icon-clion", icon: "icon-clion", name: "Clion", color: '#22DD86' },
      { key: "icon-clion-alt", icon: "icon-clion-alt", name: "Clion", color: '#22DD86' },
      { key: "icon-codeanywhere", icon: "icon-codeanywhere", name: "CodeAnywhere", color: '#7E3F98' },
      { key: "icon-code", icon: "icon-code", name: 'Code', color: null },
      { key: "icon-codenvy", icon: "icon-codenvy", name: "Codenvy", color: '#00FF8C' },
      { key: "icon-codenvy-alt", icon: "icon-codenvy-alt", name: "Codenvy", color: '#00FF8C' },
      { key: "icon-codepen", icon: "icon-codepen", name: "Codepen", color: '#FFDD40' },
      { key: "icon-codesandbox", icon: "icon-codesandbox", name: "Code Sandbox", color: '#40A9F3' },
      { key: "icon-code-writer", icon: "icon-code-writer", name: "Code Writer", color: '#900024' },
      { key: "icon-datagrip", icon: "icon-datagrip", name: "Datagrip", color: '#35C398' },
      { key: "icon-datagrip-alt", icon: "icon-datagrip-alt", name: "Datagrip", color: '#35C398' },
      { key: "icon-dotcover", icon: "icon-dotcover", name: "Dotcover", color: '#F87200' },
      { key: "icon-dotcover-alt", icon: "icon-dotcover-alt", name: "Dotcover", color: '#F87200' },
      { key: "icon-dotmemory", icon: "icon-dotmemory", name: "Dotmemory", color: '#7663F6' },
      { key: "icon-dotmemory-alt", icon: "icon-dotmemory-alt", name: "Dotmemory", color: '#7663F6' },
      { key: "icon-dotpeek", icon: "icon-dotpeek", name: "Dotpeek", color: '#5B7EF5' },
      { key: "icon-dotpeek-alt", icon: "icon-dotpeek-alt", name: "Dotpeek", color: '#5B7EF5' },
      { key: "icon-dottrace", icon: "icon-dottrace", name: "Dottrace", color: '#F620A4' },
      { key: "icon-dottrace-alt", icon: "icon-dottrace-alt", name: "Dottrace", color: '#F620A4' },
      { key: "icon-eclipse", icon: "icon-eclipse", name: "Eclipse", color: '#2C2255' },
      { key: "icon-goland", icon: "icon-goland", name: "Goland", color: '#39E360' },
      { key: "icon-goland-alt", icon: "icon-goland-alt", name: "Goland", color: '#39E360' },
      { key: "icon-gridsome", icon: "icon-gridsome", name: "Gridsome", color: '#00A672' },
      { key: "icon-intellij", icon: "icon-intellij", name: "IntelliJ", color: '#9451A1' },
      { key: "icon-intellij-alt", icon: "icon-intellij-alt", name: "IntelliJ", color: '#9451A1' },
      { key: "icon-lona", icon: "icon-lona", name: "Lona Studio", color: '#F885A0' },
      { key: "icon-mps", icon: "icon-mps", name: "Mps", color: '#129FD4' },
      { key: "icon-netbeans", icon: "icon-netbeans", name: "Netbeans", color: '#1B6AC6' },
      { key: "icon-netbeans-alt", icon: "icon-netbeans-alt", name: "Netbeans", color: '#1B6AC6' },
      { key: "icon-notepadpp", icon: "icon-notepadpp", name: "Notepad++", color: '#7DC56E' },
      { key: "icon-notepadpp-alt", icon: "icon-notepadpp-alt", name: "Notepad++", color: '#7DC56E' },
      { key: "icon-phpmyadmin", icon: "icon-phpmyadmin", name: "PhpMyAdmin", color: '#F89400' },
      { key: "icon-phpmyadmin-alt", icon: "icon-phpmyadmin-alt", name: "PhpMyAdmin", color: '#F89400' },
      { key: "icon-phpstorm", icon: "icon-phpstorm", name: "Phpstorm", color: '#904CED' },
      { key: "icon-phpstorm-alt", icon: "icon-phpstorm-alt", name: "Phpstorm", color: '#904CED' },
      { key: "icon-pycharm", icon: "icon-pycharm", name: "Pycharm", color: '#FDFA4D' },
      { key: "icon-pycharm-alt", icon: "icon-pycharm-alt", name: "Pycharm", color: '#FDFA4D' },
      { key: "icon-resharper", icon: "icon-resharper", name: "Resharper", color: '#BF0C54' },
      { key: "icon-resharper-alt", icon: "icon-resharper-alt", name: "Resharper", color: '#BF0C54' },
      { key: "icon-resharperpp", icon: "icon-resharperpp", name: "Resharper++", color: '#BF0C54' },
      { key: "icon-resharperpp-alt", icon: "icon-resharperpp-alt", name: "Resharper++", color: '#BF0C54' },
      { key: "icon-rider", icon: "icon-rider", name: "Rider", color: '#EFA112' },
      { key: "icon-rider-alt", icon: "icon-rider-alt", name: "Rider", color: '#EFA112' },
      { key: "icon-rubymine", icon: "icon-rubymine", name: "Rubymine", color: '#F81E51' },
      { key: "icon-rubymine-alt", icon: "icon-rubymine-alt", name: "Rubymine", color: '#F81E51' },
      { key: "icon-sqldeveloper", icon: "icon-sqldeveloper", name: "SQL Developer", color: '#44AC4D' },
      { key: "icon-sqlworkbench", icon: "icon-sqlworkbench", name: "SQL Workbench", color: '#25557C' },
      { key: "icon-stackblitz", icon: "icon-stackblitz", name: "Stackblitz", color: '#0076C8' },
      { key: "icon-sublime-text", icon: "icon-sublime-text", name: "Sublime Text", color: '#F89400' },
      { key: "icon-vim", icon: "icon-vim", name: "Vim", color: '#019833' },
      { key: "icon-vim-alt", icon: "icon-vim-alt", name: "Vim", color: '#019833' },
      { key: "icon-visual-studio", icon: "icon-visual-studio", name: "Visual Studio", color: '#58008B' },
      { key: "icon-vscode", icon: "icon-vscode", name: "VS Code", color: '#3C99D4' },
      { key: "icon-webstorm", icon: "icon-webstorm", name: "Webstorm", color: '#02CCD8' },
      { key: "icon-webstorm-alt", icon: "icon-webstorm-alt", name: "Webstorm", color: '#02CCD8' },
      { key: "icon-xcode", icon: "icon-xcode", name: "XCode", color: '#539FFF' },
    ]
  },
  {
    id: 'hardware',
    name: 'Hardware',
    icons: [
      { key: "icon-arduino", icon: "icon-arduino", name: "Arduino", color: '#00979C' },
      { key: "icon-bluetooth", icon: "icon-bluetooth", name: "Bluetooth", color: '#0083FD' },
      { key: "icon-bluetooth-alt", icon: "icon-bluetooth-alt", name: "Bluetooth", color: '#0083FD' },
      { key: "icon-cd", icon: "icon-cd", name: "CD", color: null },
      { key: "icon-chip", icon: "icon-chip", name: "Chip", color: null },
      { key: "icon-computer", icon: "icon-computer", name: "Computer", color: null },
      { key: "icon-disk", icon: "icon-disk", name: "Disk", color: null },
      { key: "icon-electronic-board", icon: "icon-electronic-board", name: "Electronic Board", color: null },
      { key: "icon-graphic-card", icon: "icon-graphic-card", name: "Graphic Card", color: null },
      { key: "icon-keyboard", icon: "icon-keyboard", name: "Keyboard", color: null },
      { key: "icon-mouse", icon: "icon-mouse", name: "Mouse", color: null },
      { key: "icon-phone", icon: "icon-phone", name: "Phone", color: null },
      { key: "icon-powersupply", icon: "icon-powersupply", name: "Power Supply", color: null },
      { key: "icon-processor", icon: "icon-processor", name: "Processor", color: null },
      { key: "icon-ram", icon: "icon-ram", name: "RAM", color: null },
      { key: "icon-raspberry", icon: "icon-raspberry", name: "Raspberry", color: '#E42978' },
      { key: "icon-responsive", icon: "icon-responsive", name: "Responsive", color: null },
      { key: "icon-screen", icon: "icon-screen", name: "Screen", color: null },
      { key: "icon-server", icon: "icon-server", name: "Server", color: null },
      { key: "icon-wifi", icon: "icon-wifi", name: "Wifi", color: null },
    ]
  },
  {
    id: 'recruitment',
    name: 'Recruitment Websites',
    icons: [
      { key: "icon-cadremploi", icon: "icon-cadremploi", name: "Cadremploi", color: '#27A4D6' },
      { key: "icon-cadremploi-alt", icon: "icon-cadremploi-alt", name: "Cadremploi", color: '#27A4D6' },
      { key: "icon-indeed", icon: "icon-indeed", name: "Indeed", color: '#2164F2' },
      { key: "icon-indeed-alt", icon: "icon-indeed-alt", name: "Indeed", color: '#2164F2' },
      { key: "icon-linkedin", icon: "icon-linkedin", name: "LinkedIn", color: '#007BB6' },
      { key: "icon-linkedin-alt", icon: "icon-linkedin-alt", name: "LinkedIn", color: '#007BB6' },
      { key: "icon-linkedin-alt2", icon: "icon-linkedin-alt2", name: "LinkedIn", color: '#007BB6' },
      { key: "icon-monster", icon: "icon-monster", name: "Monster", color: '#683594' },
      { key: "icon-monster-alt", icon: "icon-monster-alt", name: "Monster", color: '#683594' },
      { key: "icon-viadeo", icon: "icon-viadeo", name: "Viadeo", color: '#EE7252' },
      { key: "icon-viadeo-alt", icon: "icon-viadeo-alt", name: "Viadeo", color: '#EE7252' },
      { key: "icon-welovedevs", icon: "icon-welovedevs", name: "WeLoveDevs", color: '#2A00B4' },
    ]
  },
  {
    id: 'training',
    name: 'Training Websites',
    icons: [
      { key: "icon-codeacademy", icon: "icon-codeacademy", name: "CodeAcademy", color: '#141C3B' },
      { key: "icon-codeschool", icon: "icon-codeschool", name: "Code School", color: '#3AA7BD' },
      { key: "icon-coursera", icon: "icon-coursera", name: "Coursera", color: '#3972B8' },
      { key: "icon-datacamp", icon: "icon-datacamp", name: "Datacamp", color: '#33AACC' },
      { key: "icon-edx", icon: "icon-edx", name: "edX", color: '#B72667' },
      { key: "icon-linkedin-learning", icon: "icon-linkedin-learning", name: "LinkedIn Learning", color: '#007BB6' },
      { key: "icon-linkedin-learning-alt", icon: "icon-linkedin-learning-alt", name: "LinkedIn Learning", color: '#007BB6' },
      { key: "icon-livementor", icon: "icon-livementor", name: "LiveMentor", color: '#F7C948' },
      { key: "icon-livementor-alt", icon: "icon-livementor-alt", name: "LiveMentor", color: '#F7C948' },
      { key: "icon-livementor-alt2", icon: "icon-livementor-alt2", name: "LiveMentor", color: '#F7C948' },
      { key: "icon-mdn", icon: "icon-mdn", name: "MDN", color: '#83D0F2' },
      { key: "icon-mdn-alt", icon: "icon-mdn-alt", name: "MDN", color: '#83D0F2' },
      { key: "icon-microsoft-learn", icon: "icon-microsoft-learn", name: "Microsoft Learn", color: '#4DB2FF' },
      { key: "icon-moodle", icon: "icon-moodle", name: "Moodle", color: '#F98012' },
      { key: "icon-moodle-alt", icon: "icon-moodle-alt", name: "Moodle", color: '#F98012' },
      { key: "icon-mva", icon: "icon-mva", name: "MVA", color: '#00B7EB' },
      { key: "icon-mva-alt", icon: "icon-mva-alt", name: "MVA", color: '#00B7EB' },
      { key: "icon-newrelic", icon: "icon-newrelic", name: "New Relic", color: '#008C99' },
      { key: "icon-newrelic-alt", icon: "icon-newrelic-alt", name: "New Relic", color: '#008C99' },
      { key: "icon-openclassrooms", icon: "icon-openclassrooms", name: "Open Classrooms", color: '#F36A10' },
      { key: "icon-openclassrooms-alt", icon: "icon-openclassrooms-alt", name: "Open Classrooms", color: '#F36A10' },
      { key: "icon-pluralsight", icon: "icon-pluralsight", name: "PluralSight", color: '#231F20' },
      { key: "icon-qwiklabs", icon: "icon-qwiklabs", name: "Qwiklabs", color: '#F5CD0E' },
      { key: "icon-qwiklabs-alt", icon: "icon-qwiklabs-alt", name: "Qwiklabs", color: '#F5CD0E' },
      { key: "icon-skillvalue", icon: "icon-skillvalue", name: "SkillValue", color: '#F7BC2F' },
      { key: "icon-socialmediapro", icon: "icon-socialmediapro", name: "SocialMediaPro", color: '#EC008C' },
      { key: "icon-socialmediapro-alt", icon: "icon-socialmediapro-alt", name: "SocialMediaPro", color: '#EC008C' },
      { key: "icon-socialmediapro-alt2", icon: "icon-socialmediapro-alt2", name: "SocialMediaPro", color: '#EC008C' },
      { key: "icon-socialmediapro-alt3", icon: "icon-socialmediapro-alt3", name: "SocialMediaPro", color: '#EC008C' },
      { key: "icon-stackoverflow", icon: "icon-stackoverflow", name: "Stack Overflow", color: '#F48024' },
      { key: "icon-udacity", icon: "icon-udacity", name: "Udacity", color: '#00B2E4' },
      { key: "icon-udemy", icon: "icon-udemy", name: "uDemy", color: '#EA5252' },
    ]
  },
  {
    id: 'browser',
    name: 'Browsers',
    icons: [
      { key: "icon-chrome", icon: "icon-chrome", name: "Chrome", color: '#4E8DF6' },
      { key: "icon-edge", icon: "icon-edge", name: "Edge", color: '#0078D7' },
      { key: "icon-firefox", icon: "icon-firefox", name: "Firefox", color: '#FD6655' },
      { key: "icon-firefox-alt", icon: "icon-firefox-alt", name: "Firefox", color: '#FD6655' },
      { key: "icon-internet-explorer", icon: "icon-internet-explorer", name: "Internet Explorer", color: '#35A0DC' },
      { key: "icon-opera", icon: "icon-opera", name: "Opera", color: '#FF1A2E' },
      { key: "icon-safari", icon: "icon-safari", name: "Safari", color: '#139BD5' },
    ]
  },
  {
    id: 'db',
    name: 'Databases',
    icons: [
      { key: "icon-cassandra", icon: "icon-cassandra", name: "Cassandra", color: '#1182AE' },
      { key: "icon-consul", icon: "icon-consul", name: "Consul", color: '#CA2171' },
      { key: "icon-database", icon: "icon-database", name: "Database", color: null },
      { key: "icon-elastic-search", icon: "icon-elastic-search", name: "Elastic Search", color: '#07A5DE' },
      { key: "icon-elastic-search-alt", icon: "icon-elastic-search-alt", name: "Elastic Search", color: '#07A5DE' },
      { key: "icon-firebase", icon: "icon-firebase", name: "Firebase", color: '#F67F00' },
      { key: "icon-firebase-alt", icon: "icon-firebase-alt", name: "Firebase", color: '#F67F00' },
      { key: "icon-hadoop", icon: "icon-hadoop", name: "Hadoop", color: '#6CCFF6' },
      { key: "icon-hbase", icon: "icon-hbase", name: "HBase", color: '#BA160C' },
      { key: "icon-hbase-alt", icon: "icon-hbase-alt", name: "HBase", color: '#BA160C' },
      { key: "icon-hfsql", icon: "icon-hfsql", name: "HFsql", color: '#C73536' },
      { key: "icon-hfsql-alt", icon: "icon-hfsql-alt", name: "HFsql", color: '#C73536' },
      { key: "icon-hive", icon: "icon-hive", name: "Hive", color: '#FDEE21' },
      { key: "icon-hive-alt", icon: "icon-hive-alt", name: "Hive", color: '#FDEE21' },
      { key: "icon-hypersql", icon: "icon-hypersql", name: "HyperSQL", color: '#A0C2E7' },
      { key: "icon-mariadb", icon: "icon-mariadb", name: "MariaDB", color: '#C0765A' },
      { key: "icon-mongodb", icon: "icon-mongodb", name: "Mongo DB", color: '#459C45' },
      { key: "icon-mysql", icon: "icon-mysql", name: "MySQL", color: '#00688F' },
      { key: "icon-neo4j", icon: "icon-neo4j", name: "Neo4J", color: '#008CC2' },
      { key: "icon-neo4j-alt", icon: "icon-neo4j-alt", name: "Neo4J", color: '#008CC2' },
      { key: "icon-postgre", icon: "icon-postgre", name: "Postgre", color: '#336791' },
      { key: "icon-redis", icon: "icon-redis", name: "Redis", color: '#D82C20' },
      { key: "icon-rethinkdb", icon: "icon-rethinkdb", name: "RethinkDB", color: '#179998' },
      { key: "icon-sqlite", icon: "icon-sqlite", name: "SQLite", color: '#003244' },
      { key: "icon-sqoop", icon: "icon-sqoop", name: "Sqoop", color: '#4AB457' },
      { key: "icon-sqoop-alt", icon: "icon-sqoop-alt", name: "Sqoop", color: '#4AB457' },
    ]
  },
  {
    id: 'mobile',
    name: 'Mobile',
    icons: [
      { key: "icon-android", icon: "icon-android", name: "Android", color: '#32DE84' },
      { key: "icon-android-alt", icon: "icon-android-alt", name: "Android", color: '#32DE84' },
      { key: "icon-appcelerator", icon: "icon-appcelerator", name: "Appcelerator", color: '#AB1B32' },
      { key: "icon-appcelerator-alt", icon: "icon-appcelerator-alt", name: "Appcelerator", color: '#AB1B32' },
      { key: "icon-appstore", icon: "icon-appstore", name: "App Store", color: '#0C91F6' },
      { key: "icon-appstore-alt", icon: "icon-appstore-alt", name: "App Store", color: '#0C91F6' },
      { key: "icon-cordova", icon: "icon-cordova", name: "Cordova", color: '#2D3A45' },
      { key: "icon-expo", icon: "icon-expo", name: "Expo", color: '#01001F' },
      { key: "icon-expo-alt", icon: "icon-expo-alt", name: "Expo", color: '#01001F' },
      { key: "icon-expo-client", icon: "icon-expo-client", name: "Expo Client", color: '#01001F' },
      { key: "icon-flutter", icon: "icon-flutter", name: "Flutter", color: '#67B7F7' },
      { key: "icon-ionic", icon: "icon-ionic", name: "Ionic", color: '#478AFF' },
      { key: "icon-nativescript", icon: "icon-nativescript", name: "NativeScript", color: '#3C5AFD' },
      { key: "icon-nativescript-alt", icon: "icon-nativescript-alt", name: "NativeScript", color: '#3C5AFD' },
      { key: "icon-phonegap", icon: "icon-phonegap", name: "PhoneGap", color: '#333333' },
      { key: "icon-playstore", icon: "icon-playstore", name: "Play Store", color: '#40AAC0' },
      { key: "icon-react-native", icon: "icon-react-native", name: "React Native", color: '#61DAFB' },
      { key: "icon-swift", icon: "icon-swift", name: "Swift", color: '#ED523F' },
      { key: "icon-testflight", icon: "icon-testflight", name: "Testflight", color: '#1E9BF5' },
    ]
  },
  {
    id: 'office',
    name: 'Office',
    icons: [
      { key: "icon-access", icon: "icon-access", name: "Access", color: '#AD2234' },
      { key: "icon-drawio", icon: "icon-drawio", name: "DrawIO", color: '#E98307' },
      { key: "icon-excel", icon: "icon-excel", name: "Excel", color: '#127B42' },
      { key: "icon-google-docs", icon: "icon-google-docs", name: "Google Docs", color: '#508CEE' },
      { key: "icon-google-draw", icon: "icon-google-draw", name: "Google Draw", color: '#D34432' },
      { key: "icon-google-drive", icon: "icon-google-drive", name: "Google Drive", color: '#4383EE' },
      { key: "icon-google-forms", icon: "icon-google-forms", name: "Google Forms", color: '#6438B2' },
      { key: "icon-google-sheets", icon: "icon-google-sheets", name: "Google Sheets", color: '#21A063' },
      { key: "icon-google-sites", icon: "icon-google-sites", name: "Google Sites", color: '#4C5CB6' },
      { key: "icon-google-slides", icon: "icon-google-slides", name: "Google Slides", color: '#EDAF00' },
      { key: "icon-office", icon: "icon-office", name: "Office", color: '#E63A00' },
      { key: "icon-office-alt", icon: "icon-office-alt", name: "Office", color: '#E63A00' },
      { key: "icon-onenote", icon: "icon-onenote", name: "Onenote", color: '#7D3778' },
      { key: "icon-powerpoint", icon: "icon-powerpoint", name: "Powerpoint", color: '#CA4826' },
      { key: "icon-prezi", icon: "icon-prezi", name: "Prezi", color: '#1363C4' },
      { key: "icon-prezi-alt", icon: "icon-prezi-alt", name: "Prezi", color: '#1363C4' },
      { key: "icon-protoio", icon: "icon-protoio", name: "ProtoIO", color: '#2CA7C1' },
      { key: "icon-protoio-alt", icon: "icon-protoio-alt", name: "ProtoIO", color: '#2CA7C1' },
      { key: "icon-protoio-alt2", icon: "icon-protoio-alt2", name: "ProtoIO", color: '#2CA7C1' },
      { key: "icon-publisher", icon: "icon-publisher", name: "Publisher", color: '#087068' },
      { key: "icon-sharepoint", icon: "icon-sharepoint", name: "Sharepoint", color: '#05868B' },
      { key: "icon-visio", icon: "icon-visio", name: "Visio", color: '#1958B7' },
      { key: "icon-word", icon: "icon-word", name: "Word", color: '#2A5697' },
      { key: "icon-box", icon: "icon-box", name: "Box", color: '#0071F7' },
      { key: "icon-dropbox", icon: "icon-dropbox", name: "Dropbox", color: '#0062FF' },
      { key: "icon-dropbox-alt", icon: "icon-dropbox-alt", name: "Dropbox", color: '#0062FF' },
      { key: "icon-gmail", icon: "icon-gmail", name: "GMail", color: '#CF3930' },
      { key: "icon-mattermost", icon: "icon-mattermost", name: "Mattermost", color: '#222222' },
      { key: "icon-mega", icon: "icon-mega", name: "Mega", color: '#D9272E' },
      { key: "icon-mega-alt", icon: "icon-mega-alt", name: "Mega", color: '#D9272E' },
      { key: "icon-onedrive", icon: "icon-onedrive", name: "Onedrive", color: '#0078D4' },
      { key: "icon-onedrive-alt", icon: "icon-onedrive-alt", name: "Onedrive", color: '#0078D4' },
      { key: "icon-openvpn", icon: "icon-openvpn", name: "OpenVPN", color: '#F48222' },
      { key: "icon-openvpn-alt", icon: "icon-openvpn-alt", name: "OpenVPN", color: '#F48222' },
      { key: "icon-outlook", icon: "icon-outlook", name: "Outlook", color: '#1581DB' },
      { key: "icon-skype", icon: "icon-skype", name: "Skype", color: '#28A8EA' },
      { key: "icon-skype-alt", icon: "icon-skype-alt", name: "Skype", color: '#28A8EA' },
      { key: "icon-slack", icon: "icon-slack", name: "Slack", color: '#D81C57' },
      { key: "icon-glowbl", icon: "icon-glowbl", name: "Glowbl", color: '#9B81C8' },
      { key: "icon-glowbl-alt", icon: "icon-glowbl-alt", name: "Glowbl", color: '#9B81C8' },
      { key: "icon-jira", icon: "icon-jira", name: "Jira", color: '#003265' },
      { key: "icon-kanboard", icon: "icon-kanboard", name: "Kanboard", color: '#2A0000' },
      { key: "icon-teams", icon: "icon-teams", name: "Teams", color: '#5458AF' },
      { key: "icon-teamviewer", icon: "icon-teamviewer", name: "TeamViewer", color: '#0A7BD9' },
      { key: "icon-trello", icon: "icon-trello", name: "Trello", color: '#0081CC' },
      { key: "icon-yammer", icon: "icon-yammer", name: "Yammer", color: '#0078D4' },
      { key: "icon-zimbra", icon: "icon-zimbra", name: "Zimbra", color: '#F05922' },
      { key: "icon-zimbra-alt", icon: "icon-zimbra-alt", name: "Zimbra", color: '#F05922' },
      { key: "icon-ammyyadmin", icon: "icon-ammyyadmin", name: "Ammyy Admin", color: '#E92018' },
      { key: "icon-anydesk-alt", icon: "icon-anydesk-alt", name: "Anydesk", color: '#F54035' },
      { key: "icon-stride", icon: "icon-stride", name: "Stride", color: '#2580F7' },
      { key: "icon-anydesk", icon: "icon-anydesk", name: "Anydesk", color: '#F54035' },
      { key: "icon-xmind", icon: "icon-xmind", name: "XMind", color: '#FF291E' },
      { key: "icon-wireshark", icon: "icon-wireshark", name: "Wireshark", color: '#2862A2' },
    ]
  },
  {
    id: 'social',
    name: 'Social Networks',
    icons: [
      { key: "icon-badoo", icon: "icon-badoo", name: "Badoo", color: '#7D42F9' },
      { key: "icon-badoo-alt", icon: "icon-badoo-alt", name: "Badoo", color: '#7D42F9' },
      { key: "icon-baidu", icon: "icon-baidu", name: "Baidu", color: '#2319DC' },
      { key: "icon-baidu-alt", icon: "icon-baidu-alt", name: "Baidu", color: '#2319DC' },
      { key: "icon-deviantart", icon: "icon-deviantart", name: "Deviant Art", color: '#45B748' },
      { key: "icon-deviantart-alt", icon: "icon-deviantart-alt", name: "Deviant Art", color: '#45B748' },
      { key: "icon-discord", icon: "icon-discord", name: "Discord", color: '#6C8BF5' },
      { key: "icon-discord-alt", icon: "icon-discord-alt", name: "Discord", color: '#6C8BF5' },
      { key: "icon-discord-alt2", icon: "icon-discord-alt2", name: "Discord", color: '#6C8BF5' },
      { key: "icon-duo", icon: "icon-duo", name: "Duo", color: '#1A73E8' },
      { key: "icon-facebook", icon: "icon-facebook", name: "Facebook", color: '#4267B2' },
      { key: "icon-facebook-alt", icon: "icon-facebook-alt", name: "Facebook", color: '#4267B2' },
      { key: "icon-flickr", icon: "icon-flickr", name: "Flickr", color: '#0063DB' },
      { key: "icon-flickr-alt", icon: "icon-flickr-alt", name: "Flickr", color: '#0063DB' },
      { key: "icon-foursquare", icon: "icon-foursquare", name: "Foursquare", color: '#F94877' },
      { key: "icon-gaia", icon: "icon-gaia", name: "Gaia", color: '#605270' },
      { key: "icon-gaia-alt", icon: "icon-gaia-alt", name: "Gaia", color: '#605270' },
      { key: "icon-hangouts", icon: "icon-hangouts", name: "Hangouts", color: '#2EB634' },
      { key: "icon-instagram", icon: "icon-instagram", name: "Instagram", color: '#C1276B' },
      { key: "icon-instagram-alt", icon: "icon-instagram-alt", name: "Instagram", color: '#C1276B' },
      { key: "icon-line", icon: "icon-line", name: "Line", color: '#00B900' },
      { key: "icon-line-alt", icon: "icon-line-alt", name: "Line", color: '#00B900' },
      { key: "icon-line-alt2", icon: "icon-line-alt2", name: "Line", color: '#00B900' },
      { key: "icon-meetup", icon: "icon-meetup", name: "Meetup", color: '#ED1C40' },
      { key: "icon-meetup-alt", icon: "icon-meetup-alt", name: "Meetup", color: '#ED1C40' },
      { key: "icon-messenger", icon: "icon-messenger", name: "Messenger", color: '#0096FF' },
      { key: "icon-mixer", icon: "icon-mixer", name: "Mixer", color: '#17244E' },
      { key: "icon-mixer-alt", icon: "icon-mixer-alt", name: "Mixer", color: '#17244E' },
      { key: "icon-myspace", icon: "icon-myspace", name: "MySpace", color: '#012F9E' },
      { key: "icon-myspace-alt", icon: "icon-myspace-alt", name: "MySpace", color: '#012F9E' },
      { key: "icon-pinterest", icon: "icon-pinterest", name: "Pinterest", color: '#E00019' },
      { key: "icon-quora", icon: "icon-quora", name: "Quora", color: '#A82300' },
      { key: "icon-quora-alt", icon: "icon-quora-alt", name: "Quora", color: '#A82300' },
      { key: "icon-qq", icon: "icon-qq", name: "QQ", color: '#FE2901' },
      { key: "icon-qzone", icon: "icon-qzone", name: "QZone", color: '#000000' },
      { key: "icon-reddit", icon: "icon-reddit", name: "Reddit", color: '#FF4500' },
      { key: "icon-reddit-alt", icon: "icon-reddit-alt", name: "Reddit", color: '#FF4500' },
      { key: "icon-reddit-alt2", icon: "icon-reddit-alt2", name: "Reddit", color: '#FF4500' },
      { key: "icon-sinaweibo", icon: "icon-sinaweibo", name: "SinaWeibo", color: '#D0202F' },
      { key: "icon-sinaweibo-alt", icon: "icon-sinaweibo-alt", name: "SinaWeibo", color: '#D0202F' },
      { key: "icon-snapchat", icon: "icon-snapchat", name: "Snapchat", color: '#FFFC01' },
      { key: "icon-snapchat-alt", icon: "icon-snapchat-alt", name: "Snapchat", color: '#FFFC01' },
      { key: "icon-telegram", icon: "icon-telegram", name: "Telegram", color: '#2FA7DB' },
      { key: "icon-telegram-alt", icon: "icon-telegram-alt", name: "Telegram", color: '#2FA7DB' },
      { key: "icon-tiktok", icon: "icon-tiktok", name: "Tiktok", color: '#000000' },
      { key: "icon-tumblr", icon: "icon-tumblr", name: "Tumblr", color: '#000000' },
      { key: "icon-tumblr-alt", icon: "icon-tumblr-alt", name: "Tumblr", color: '#000000' },
      { key: "icon-twitch", icon: "icon-twitch", name: "Twitch", color: '#6441A4' },
      { key: "icon-twitch-alt", icon: "icon-twitch-alt", name: "Twitch", color: '#6441A4' },
      { key: "icon-twitter", icon: "icon-twitter", name: "Twitter", color: '#1DA1F2' },
      { key: "icon-viber", icon: "icon-viber", name: "Viber", color: '#7C529E' },
      { key: "icon-viber-alt", icon: "icon-viber-alt", name: "Viber", color: '#7C529E' },
      { key: "icon-vine", icon: "icon-vine", name: "Vine", color: '#00B386' },
      { key: "icon-vine-alt", icon: "icon-vine-alt", name: "Vine", color: '#00B386' },
      { key: "icon-vkontakte", icon: "icon-vkontakte", name: "VKontakte", color: '#5181B8' },
      { key: "icon-vkontakte-alt", icon: "icon-vkontakte-alt", name: "VKontakte", color: '#5181B8' },
      { key: "icon-wechat", icon: "icon-wechat", name: "WeChat", color: '#04D669' },
      { key: "icon-wechat-alt", icon: "icon-wechat-alt", name: "WeChat", color: '#04D669' },
      { key: "icon-whatsapp", icon: "icon-whatsapp", name: "WhatsApp", color: '#00E676' },
      { key: "icon-whatsapp-alt", icon: "icon-whatsapp-alt", name: "WhatsApp", color: '#00E676' },
      { key: "icon-whereby", icon: "icon-whereby", name: "Whereby", color: '#000000' },
      { key: "icon-whereby-alt", icon: "icon-whereby-alt", name: "Whereby", color: '#000000' },
      { key: "icon-xing", icon: "icon-xing", name: "Xing", color: '#006567' },
      { key: "icon-xing-alt", icon: "icon-xing-alt", name: "Xing", color: '#006567' },
      { key: "icon-xing-alt2", icon: "icon-xing-alt2", name: "Xing", color: '#006567' },
      { key: "icon-youtube", icon: "icon-youtube", name: "YouTube", color: '#FF0000' },
      { key: "icon-youtube-alt", icon: "icon-youtube-alt", name: "YouTube", color: '#FF0000' },
    ]
  },
  {
    id: 'graphics',
    name: 'Graphics & 3D',
    icons: [
      { key: "icon-aftereffects", icon: "icon-aftereffects", name: "After Effects", color: '#D291FF' },
      { key: "icon-autocad", icon: "icon-autocad", name: "Autocad", color: '#F73E40' },
      { key: "icon-behance", icon: "icon-behance", name: "Behance", color: '#1769FF' },
      { key: "icon-behance-alt", icon: "icon-behance-alt", name: "Behance", color: '#1769FF' },
      { key: "icon-catia", icon: "icon-catia", name: "Catia", color: '#120C80' },
      { key: "icon-blender", icon: "icon-blender", name: "Blender", color: '#265787' },
      { key: "icon-cinema4d", icon: "icon-cinema4d", name: "Cinema4D", color: '#1F2A7A' },
      { key: "icon-dribbble", icon: "icon-dribbble", name: "Dribbble", color: '#E74D89' },
      { key: "icon-dribbble-alt", icon: "icon-dribbble-alt", name: "Dribbble", color: '#E74D89' },
      { key: "icon-fontello", icon: "icon-fontello", name: "Fontello", color: '#000000' },
      { key: "icon-fontello-alt", icon: "icon-fontello-alt", name: "Fontello", color: '#000000' },
      { key: "icon-gimp", icon: "icon-gimp", name: "Gimp", color: '#60573A' },
      { key: "icon-illustrator", icon: "icon-illustrator", name: "Illustrator", color: '#F57F22' },
      { key: "icon-indesign", icon: "icon-indesign", name: "InDesign", color: '#FF3F94' },
      { key: "icon-inkscape", icon: "icon-inkscape", name: "Inkscape", color: '#000000' },
      { key: "icon-lightroom", icon: "icon-lightroom", name: "Lightroom", color: '#3DF0F0' },
      { key: "icon-lunacy", icon: "icon-lunacy", name: "Lunacy", color: '#0092EB' },
      { key: "icon-photoshop", icon: "icon-photoshop", name: "PhotoShop", color: '#1EE0FF' },
      { key: "icon-photoview", icon: "icon-photoview", name: "Photoview", color: '#9EA09F' },
      { key: "icon-poweruser", icon: "icon-poweruser", name: "PowerUser", color: '#021D61' },
      { key: "icon-sketch", icon: "icon-sketch", name: "Sketch", color: '#ECA436' },
      { key: "icon-sketch-alt", icon: "icon-sketch-alt", name: "Sketch", color: '#ECA436' },
      { key: "icon-solidworks", icon: "icon-solidworks", name: "Solidworks", color: '#ED1C24' },
      { key: "icon-solidworks-alt", icon: "icon-solidworks-alt", name: "Solidworks", color: '#ED1C24' },
      { key: "icon-xd", icon: "icon-xd", name: "Xd", color: '#FF26BE' },
    ]
  },
  {
    id: 'market',
    name: 'Analysis & Marketing',
    icons: [
      { key: "icon-appdynamics", icon: "icon-appdynamics", name: "AppDynamics", color: '#1C252E' },
      { key: "icon-brandflow", icon: "icon-brandflow", name: "Brandflow", color: '#1CAAE2' },
      { key: "icon-google-adsense", icon: "icon-google-adsense", name: "Google Adsense", color: '#F6B80D' },
      { key: "icon-google-ads", icon: "icon-google-ads", name: "Google Ads", color: '#4285F4' },
      { key: "icon-google-analytics", icon: "icon-google-analytics", name: "Google Analytics", color: '#FFC71C' },
      { key: "icon-google-tag-manager", icon: "icon-google-tag-manager", name: "Google Tag Manager", color: '#4285F4' },
      { key: "icon-mailchimp", icon: "icon-mailchimp", name: "Mailchimp", color: '#000000' },
      { key: "icon-majestic", icon: "icon-majestic", name: "Majestic", color: '#E62A28' },
      { key: "icon-salesforce", icon: "icon-salesforce", name: "Salesforce", color: '#1796C1' },
      { key: "icon-soasta", icon: "icon-soasta", name: "Soasta", color: '#1E4281' },
      { key: "icon-splunk", icon: "icon-splunk", name: "Splunk", color: '#979797' },
    ]
  },
  {
    id: 'version',
    name: 'Code Versioning',
    icons: [
      { key: "icon-bitbucket", icon: "icon-bitbucket", name: "BitBucket", color: '#1F5081' },
      { key: "icon-git", icon: "icon-git", name: "Git", color: '#F05033' },
      { key: "icon-gitbash", icon: "icon-gitbash", name: "Git Bash", color: '#7DAEF8' },
      { key: "icon-github", icon: "icon-github", name: "GitHub", color: '#000000' },
      { key: "icon-gitlab", icon: "icon-gitlab", name: "GitLab", color: '#FC6D26' },
      { key: "icon-gitkraken", icon: "icon-gitkraken", name: "Git Kraken", color: '#179287' },
      { key: "icon-hub", icon: "icon-hub", name: "Hub", color: '#1D9CEB' },
      { key: "icon-hub-alt", icon: "icon-hub-alt", name: "Hub", color: '#1D9CEB' },
      { key: "icon-subversive", icon: "icon-subversive", name: "Subversive", color: '#7D98C4' },
      { key: "icon-subversive-alt", icon: "icon-subversive-alt", name: "Subversive", color: '#7D98C4' },
      { key: "icon-tortoise", icon: "icon-tortoise", name: "Tortoise", color: '#809CC8' },
      { key: "icon-upsource", icon: "icon-upsource", name: "Upsource", color: '#E5772C' },
      { key: "icon-upsource-alt", icon: "icon-upsource-alt", name: "Upsource", color: '#E5772C' },
    ]
  },
  {
    id: 'gis',
    name: 'GIS & Geo',
    icons: [
      { key: "icon-anydwg", icon: "icon-anydwg", name: "AnyDWG", color: '#73828C' },
      { key: "icon-bimserver", icon: "icon-bimserver", name: "Bimserver", color: '#3A74AE' },
      { key: "icon-carto", icon: "icon-carto", name: "Carto", color: '#EB1510' },
      { key: "icon-cartodb", icon: "icon-cartodb", name: "CartoDB", color: '#6592D3' },
      { key: "icon-cartodb-alt", icon: "icon-cartodb-alt", name: "CartoDB", color: '#6592D3' },
      { key: "icon-esri", icon: "icon-esri", name: "ESRI", color: '#66B4E4' },
      { key: "icon-geoserver", icon: "icon-geoserver", name: "GeoServer", color: '#009AD0' },
      { key: "icon-giscloud", icon: "icon-giscloud", name: "GIS Cloud", color: '#146EBF' },
      { key: "icon-giscloud-alt", icon: "icon-giscloud-alt", name: "GIS Cloud", color: '#146EBF' },
      { key: "icon-leaflet", icon: "icon-leaflet", name: "Leaflet", color: '#B5E161' },
      { key: "icon-leaflet-alt", icon: "icon-leaflet-alt", name: "Leaflet", color: '#B5E161' },
      { key: "icon-google-maps", icon: "icon-google-maps", name: "Google Maps", color: '#1FA463' },
      { key: "icon-google-mymaps", icon: "icon-google-mymaps", name: "Google MyMaps", color: null },
      { key: "icon-mapbox", icon: "icon-mapbox", name: "Mapbox", color: '#395AFA' },
      { key: "icon-mapbox-alt", icon: "icon-mapbox-alt", name: "Mapbox", color: '#395AFA' },
      { key: "icon-openlayers", icon: "icon-openlayers", name: "OpenLayers", color: '#35BCCE' },
      { key: "icon-postgis", icon: "icon-postgis", name: "PostGIS", color: '#794D66' },
      { key: "icon-qgis", icon: "icon-qgis", name: "QGIS", color: '#629B30' },
      { key: "icon-qgis-alt", icon: "icon-qgis-alt", name: "QGIS", color: '#629B30' },
    ]
  },
  {
    id: 'front',
    name: 'Front-End',
    icons: [
      { key: "icon-ajax", icon: "icon-ajax", name: "Ajax", color: '#4794CA' },
      { key: "icon-babylon", icon: "icon-babylon", name: "Babylon", color: '#E16849' },
      { key: "icon-bcfont", icon: "icon-bcfont", name: "BC Font", color: '#EB2834' },
      { key: "icon-bcfont-alt", icon: "icon-bcfont-alt", name: "BC Font", color: '#EB2834' },
      { key: "icon-babylon-alt", icon: "icon-babylon-alt", name: "Babylon", color: '#E16849' },
      { key: "icon-bootstrap", icon: "icon-bootstrap", name: "Bootstrap", color: '#563D7C' },
      { key: "icon-can", icon: "icon-can", name: "can", color: '#3E7ABE' },
      { key: "icon-chartjs", icon: "icon-chartjs", name: "ChartJS", color: '#FE767A' },
      { key: "icon-coffee-script", icon: "icon-coffee-script", name: "CoffeeScript", color: '#3E2723' },
      { key: "icon-css", icon: "icon-css", name: "CSS", color: '#264DE4' },
      { key: "icon-css-alt", icon: "icon-css-alt", name: "CSS", color: '#264DE4' },
      { key: "icon-d3", icon: "icon-d3", name: "d3", color: '#F99B41' },
      { key: "icon-dc", icon: "icon-dc", name: "DC", color: '#F69837' },
      { key: "icon-dojo", icon: "icon-dojo", name: "Dojo", color: '#000000' },
      { key: "icon-flux", icon: "icon-flux", name: "Flux", color: '#67C46C' },
      { key: "icon-handlebars", icon: "icon-handlebars", name: "HandleBars", color: '#403325' },
      { key: "icon-html", icon: "icon-html", name: "HTML", color: '#DE4B25' },
      { key: "icon-html-alt", icon: "icon-html-alt", name: "HTML", color: '#DE4B25' },
      { key: "icon-initializr", icon: "icon-initializr", name: "Initializr", color: '#F16529' },
      { key: "icon-javascript", icon: "icon-javascript", name: "JavaScript", color: '#F0D91D' },
      { key: "icon-javascript-alt", icon: "icon-javascript-alt", name: "JavaScript", color: '#F0D91D' },
      { key: "icon-jquery", icon: "icon-jquery", name: "jQuery", color: '#2480B3' },
      { key: "icon-jquery-ui", icon: "icon-jquery-ui", name: "jQuery UI", color: '#FAA523' },
      { key: "icon-jquery-ui-alt", icon: "icon-jquery-ui-alt", name: "jQuery UI", color: '#FAA523' },
      { key: "icon-kendo-ui", icon: "icon-kendo-ui", name: "Kendo UI", color: '#DE622F' },
      { key: "icon-knockback", icon: "icon-knockback", name: "Knockback", color: '#333333' },
      { key: "icon-knockout", icon: "icon-knockout", name: "Knockout", color: '#E45D01' },
      { key: "icon-less", icon: "icon-less", name: "Less", color: '#1D385F' },
      { key: "icon-less-alt", icon: "icon-less-alt", name: "Less", color: '#1D385F' },
      { key: "icon-lodash", icon: "icon-lodash", name: "Lodash", color: '#3492FF' },
      { key: "icon-marionette", icon: "icon-marionette", name: "Marionette", color: '#CF2227' },
      { key: "icon-marko", icon: "icon-marko", name: "Marko", color: '#DD0044' },
      { key: "icon-materialize", icon: "icon-materialize", name: "Materialize", color: '#EB6F79' },
      { key: "icon-mdbootstrap", icon: "icon-mdbootstrap", name: "MDBootstrap", color: '#398DE3' },
      { key: "icon-modernizr", icon: "icon-modernizr", name: "Modernizr", color: '#F7529E' },
      { key: "icon-moment", icon: "icon-moment", name: "Moment", color: '#61B2A7' },
      { key: "icon-p5js", icon: "icon-p5js", name: "p5js", color: '#ED225D' },
      { key: "icon-p5js-alt", icon: "icon-p5js-alt", name: "p5js", color: '#ED225D' },
      { key: "icon-plotly", icon: "icon-plotly", name: "Plotly", color: '#119DFF' },
      { key: "icon-plotly-alt", icon: "icon-plotly-alt", name: "Plotly", color: '#119DFF' },
      { key: "icon-polyfill", icon: "icon-polyfill", name: "Polyfill", color: '#0A95C7' },
      { key: "icon-polymer", icon: "icon-polymer", name: "Polymer", color: '#E53974' },
      { key: "icon-postcss", icon: "icon-postcss", name: "PostCSS", color: '#DD3600' },
      { key: "icon-pug", icon: "icon-pug", name: "Pug", color: '#EFCCA3' },
      { key: "icon-pure-css", icon: "icon-pure-css", name: "Pure CSS", color: '#1F8DD6' },
      { key: "icon-pure-css-alt", icon: "icon-pure-css-alt", name: "Pure CSS", color: '#1F8DD6' },
      { key: "icon-redux", icon: "icon-redux", name: "Redux", color: '#764ABC' },
      { key: "icon-require", icon: "icon-require", name: "Require", color: '#F44A41' },
      { key: "icon-rxjs", icon: "icon-rxjs", name: "RxJS", color: '#EC0F8F' },
      { key: "icon-sapper", icon: "icon-sapper", name: "Sapper", color: '#159497' },
      { key: "icon-sass", icon: "icon-sass", name: "Sass", color: '#CA5B92' },
      { key: "icon-sass-alt", icon: "icon-sass-alt", name: "Sass", color: '#CA5B92' },
      { key: "icon-semantic-ui", icon: "icon-semantic-ui", name: "Semantic UI", color: '#35BDB2' },
      { key: "icon-snapsvg", icon: "icon-snapsvg", name: "SnapSVG", color: '#09B39C' },
      { key: "icon-svelte", icon: "icon-svelte", name: "Svelte", color: '#FF3E00' },
      { key: "icon-svelte-alt", icon: "icon-svelte-alt", name: "Svelte", color: '#FF3E00' },
      { key: "icon-three", icon: "icon-three", name: "Three", color: '#000000' },
      { key: "icon-tonejs", icon: "icon-tonejs", name: "ToneJS", color: '#22DBC0' },
      { key: "icon-troop", icon: "icon-troop", name: "Troop", color: '#6D321B' },
      { key: "icon-twig", icon: "icon-twig", name: "Twig", color: '#63842D' },
      { key: "icon-typescript", icon: "icon-typescript", name: "TypeScript", color: '#007ACC' },
      { key: "icon-uikit", icon: "icon-uikit", name: "UI-Kit", color: '#55B5DD' },
      { key: "icon-underscore", icon: "icon-underscore", name: "Underscore", color: '#006EB0' },
      { key: "icon-underscore-alt", icon: "icon-underscore-alt", name: "Underscore", color: '#006EB0' },
      { key: "icon-zepto", icon: "icon-zepto", name: "Zepto", color: '#8860FF' },
      { key: "icon-zingchart", icon: "icon-zingchart", name: "Zing Chart", color: '#00B5EA' },
      { key: "icon-zingchart-alt", icon: "icon-zingchart-alt", name: "Zing Chart", color: '#00B5EA' },
      { key: "icon-ampersand", icon: "icon-ampersand", name: "Ampersand", color: '#EC008C' },
      { key: "icon-angular", icon: "icon-angular", name: "Angular", color: '#DD0031' },
      { key: "icon-apollo", icon: "icon-apollo", name: "Apollo", color: '#080188' },
      { key: "icon-apollo-alt", icon: "icon-apollo-alt", name: "Apollo", color: '#080188' },
      { key: "icon-aurelia", icon: "icon-aurelia", name: "Aurelia", color: '#ED2B88' },
      { key: "icon-backbone", icon: "icon-backbone", name: "Backbone", color: '#0071B5' },
      { key: "icon-code-igniter", icon: "icon-code-igniter", name: "Code Igniter", color: '#EE4323' },
      { key: "icon-ember", icon: "icon-ember", name: "Ember", color: '#E14A30' },
      { key: "icon-flight", icon: "icon-flight", name: "Flight", color: '#00ACEE' },
      { key: "icon-foundation", icon: "icon-foundation", name: "Foundation", color: '#E4F0F7' },
      { key: "icon-gatsby", icon: "icon-gatsby", name: "Gatsby", color: '#341F63' },
      { key: "icon-gatsby-alt", icon: "icon-gatsby-alt", name: "Gatsby", color: '#341F63' },
      { key: "icon-meteor", icon: "icon-meteor", name: "Meteor", color: '#DF4D4E' },
      { key: "icon-mithril", icon: "icon-mithril", name: "Mithril", color: '#000000' },
      { key: "icon-nuxt", icon: "icon-nuxt", name: "Nuxt", color: '#00BB7F' },
      { key: "icon-nuxt-alt", icon: "icon-nuxt-alt", name: "Nuxt", color: '#00BB7F' },
      { key: "icon-quasar", icon: "icon-quasar", name: "Quasar", color: '#42A5F5' },
      { key: "icon-react", icon: "icon-react", name: "React", color: '#53C1DE' },
      { key: "icon-vuejs", icon: "icon-vuejs", name: "VueJS", color: '#41B883' },
      { key: "icon-vuejs-alt", icon: "icon-vuejs-alt", name: "VueJS", color: '#41B883' },
      { key: "icon-babel", icon: "icon-babel", name: "Babel", color: '#F1D54C' },
      { key: "icon-cypress", icon: "icon-cypress", name: "Cypress", color: '#23262E' },
      { key: "icon-cypress-alt", icon: "icon-cypress-alt", name: "Cypress", color: '#23262E' },
      { key: "icon-grunt", icon: "icon-grunt", name: "Grunt", color: '#FBA919' },
      { key: "icon-gulp", icon: "icon-gulp", name: "Gulp", color: '#DA4648' },
      { key: "icon-jasmine", icon: "icon-jasmine", name: "Jasmine", color: '#8A4182' },
      { key: "icon-jscs", icon: "icon-jscs", name: "JSCS", color: '#EBD851' },
      { key: "icon-jshint", icon: "icon-jshint", name: "JSHint", color: '#FADE42' },
      { key: "icon-karma", icon: "icon-karma", name: "Karma", color: '#56C5A8' },
      { key: "icon-mocha", icon: "icon-mocha", name: "Mocha", color: '#8D6748' },
      { key: "icon-mocha-alt", icon: "icon-mocha-alt", name: "Mocha", color: '#8D6748' },
      { key: "icon-phantomjs", icon: "icon-phantomjs", name: "PhantomJS", color: '#2FC7D5' },
      { key: "icon-protractor", icon: "icon-protractor", name: "Protractor", color: '#E23237' },
      { key: "icon-protractor-alt", icon: "icon-protractor-alt", name: "Protractor", color: '#E23237' },
      { key: "icon-styleguidist", icon: "icon-styleguidist", name: "Style Guidist", color: '#00D8FE' },
      { key: "icon-webpack", icon: "icon-webpack", name: "Webpack", color: '#1C78C0' },
    ]
  },
  {
    id: 'package',
    name: 'Package Providers',
    icons: [
      { key: "icon-bazel", icon: "icon-bazel", name: "Bazel", color: '#43A047' },
      { key: "icon-bower", icon: "icon-bower", name: "Bower", color: '#EF5734' },
      { key: "icon-composer", icon: "icon-composer", name: "Composer", color: '#5B4837' },
      { key: "icon-maven", icon: "icon-maven", name: "Maven", color: '#C4203C' },
      { key: "icon-npm", icon: "icon-npm", name: "NPM", color: '#C83E3E' },
      { key: "icon-npm-alt", icon: "icon-npm-alt", name: "NPM", color: '#C83E3E' },
      { key: "icon-yarn", icon: "icon-yarn", name: "Yarn", color: '#2C8EBB' },
      { key: "icon-yarn-alt", icon: "icon-yarn-alt", name: "Yarn", color: '#2C8EBB' },
    ]
  },
  {
    id: 'back',
    name: 'Back-End',
    icons: [
      { key: "icon-c", icon: "icon-c", name: "C", color: '#AABBCE' },
      { key: "icon-c-sharp", icon: "icon-c-sharp", name: "C#", color: '#9669DE' },
      { key: "icon-clojure", icon: "icon-clojure", name: "Clojure", color: '#90B4FE' },
      { key: "icon-cobol", icon: "icon-cobol", name: "Cobol", color: '#005CA5' },
      { key: "icon-cobol-alt", icon: "icon-cobol-alt", name: "Cobol", color: '#005CA5' },
      { key: "icon-cocos", icon: "icon-cocos", name: "Cocos", color: '#2AC2E7' },
      { key: "icon-cpp", icon: "icon-cpp", name: "C++", color: '#659AD2' },
      { key: "icon-cucumber", icon: "icon-cucumber", name: "Cucumber", color: '#00A818' },
      { key: "icon-dart", icon: "icon-dart", name: "Dart", color: '#2CB7F7' },
      { key: "icon-elixir", icon: "icon-elixir", name: "Elixir", color: '#35134A' },
      { key: "icon-elm", icon: "icon-elm", name: "elm", color: '#7FD13B' },
      { key: "icon-erlang", icon: "icon-erlang", name: "erlang", color: '#A90533' },
      { key: "icon-fsharp", icon: "icon-fsharp", name: "F#", color: '#378BBA' },
      { key: "icon-gatling", icon: "icon-gatling", name: "Gatling", color: '#E07403' },
      { key: "icon-gatling-alt", icon: "icon-gatling-alt", name: "Gatling", color: '#E07403' },
      { key: "icon-go", icon: "icon-go", name: "Go", color: '#75CEDE' },
      { key: "icon-groovy", icon: "icon-groovy", name: "Groovy", color: '#65A2C3' },
      { key: "icon-gwt", icon: "icon-gwt", name: "GWT", color: '#EE2D36' },
      { key: "icon-haskell", icon: "icon-haskell", name: "Haskell", color: '#999999' },
      { key: "icon-horizon", icon: "icon-horizon", name: "Horizon", color: '#EC9C71' },
      { key: "icon-java", icon: "icon-java", name: "Java", color: '#DB1931' },
      { key: "icon-javafx", icon: "icon-javafx", name: "JavaFX", color: '#DB1931' },
      { key: "icon-javafx-alt", icon: "icon-javafx-alt", name: "JavaFX", color: '#DB1931' },
      { key: "icon-junit", icon: "icon-junit", name: "JUnit", color: '#4E9A06' },
      { key: "icon-kotlin", icon: "icon-kotlin", name: "Kotlin", color: '#F3831D' },
      { key: "icon-latex", icon: "icon-latex", name: "Latex", color: '#000000' },
      { key: "icon-lisp", icon: "icon-lisp", name: "Lisp", color: '#BE0803' },
      { key: "icon-livecycle", icon: "icon-livecycle", name: "LiveCycle", color: '#188ECC' },
      { key: "icon-lua", icon: "icon-lua", name: "Lua", color: '#000080' },
      { key: "icon-lua-alt", icon: "icon-lua-alt", name: "Lua", color: '#000080' },
      { key: "icon-mockito", icon: "icon-mockito", name: "Mockito", color: '#82A04A' },
      { key: "icon-net", icon: "icon-net", name: ".net", color: '#682B7B' },
      { key: "icon-next", icon: "icon-next", name: "Next", color: '#000000' },
      { key: "icon-ocaml", icon: "icon-ocaml", name: "OCaml", color: '#EC6C13' },
      { key: "icon-opencv", icon: "icon-opencv", name: "OpenCV", color: '#0101FF' },
      { key: "icon-perl", icon: "icon-perl", name: "Perl", color: '#383A59' },
      { key: "icon-php", icon: "icon-php", name: "PHP", color: '#8792BF' },
      { key: "icon-python", icon: "icon-python", name: "Python", color: '#3575B0' },
      { key: "icon-r", icon: "icon-r", name: "R", color: '#2266B9' },
      { key: "icon-ruby", icon: "icon-ruby", name: "Ruby", color: '#EF0E13' },
      { key: "icon-rust", icon: "icon-rust", name: "Rust", color: '#000000' },
      { key: "icon-scala", icon: "icon-scala", name: "Scala", color: '#DE3423' },
      { key: "icon-visual-basic", icon: "icon-visual-basic", name: "Visual Basic", color: '#692A7B' },
      { key: "icon-windev", icon: "icon-windev", name: "WinDev", color: '#000000' },
      { key: "icon-windev-alt", icon: "icon-windev-alt", name: "WinDev", color: '#000000' },
      { key: "icon-adonis", icon: "icon-adonis", name: "Adonis", color: '#220052' },
      { key: "icon-express", icon: "icon-express", name: "Express", color: '#000000' },
      { key: "icon-cakephp", icon: "icon-cakephp", name: "Cake PHP", color: '#D43D44' },
      { key: "icon-django", icon: "icon-django", name: "Django", color: '#092E20' },
      { key: "icon-django-alt", icon: "icon-django-alt", name: "Django", color: '#092E20' },
      { key: "icon-fatfree", icon: "icon-fatfree", name: "Fatfree", color: null },
      { key: "icon-flask", icon: "icon-flask", name: "Flask", color: '#000000' },
      { key: "icon-krakenjs", icon: "icon-krakenjs", name: "KrakenJS", color: '#0081C2' },
      { key: "icon-krakenjs-alt", icon: "icon-krakenjs-alt", name: "KrakenJS", color: '#0081C2' },
      { key: "icon-laravel", icon: "icon-laravel", name: "Laravel", color: '#F05340' },
      { key: "icon-loopback", icon: "icon-loopback", name: "Loopback", color: '#405CFE' },
      { key: "icon-loopback-alt", icon: "icon-loopback-alt", name: "Loopback", color: '#405CFE' },
      { key: "icon-neos", icon: "icon-neos", name: "Neos", color: '#26224C' },
      { key: "icon-nest", icon: "icon-nest", name: "Nest", color: '#E0234E' },
      { key: "icon-nest-alt", icon: "icon-nest-alt", name: "Nest", color: '#E0234E' },
      { key: "icon-nodejs", icon: "icon-nodejs", name: "NodeJS", color: '#79A876' },
      { key: "icon-phalcon", icon: "icon-phalcon", name: "Phalcon", color: '#86CCAB' },
      { key: "icon-qt", icon: "icon-qt", name: "QT", color: '#41CD52' },
      { key: "icon-qt-alt", icon: "icon-qt-alt", name: "QT", color: '#41CD52' },
      { key: "icon-rubyonrails", icon: "icon-rubyonrails", name: "Ruby on Rails", color: '#CC0000' },
      { key: "icon-silex", icon: "icon-silex", name: "Silex", color: '#45585F' },
      { key: "icon-spring", icon: "icon-spring", name: "Spring", color: '#6DB33F' },
      { key: "icon-stripes", icon: "icon-stripes", name: "Stripes", color: '#6E9FD7' },
      { key: "icon-symfony", icon: "icon-symfony", name: "Symfony", color: '#000000' },
      { key: "icon-symfony-alt", icon: "icon-symfony-alt", name: "Symfony", color: '#000000' },
      { key: "icon-vaadin", icon: "icon-vaadin", name: "Vaadin", color: '#00B2F0' },
      { key: "icon-xamarin", icon: "icon-xamarin", name: "Xamarin", color: '#66ADE2' },
      { key: "icon-xamarin-alt", icon: "icon-xamarin-alt", name: "Xamarin", color: '#66ADE2' },
      { key: "icon-yeoman", icon: "icon-yeoman", name: "Yeoman", color: '#CD2323' },
      { key: "icon-yii", icon: "icon-yii", name: "Yii", color: '#EB6E2E' },
      { key: "icon-yii-alt", icon: "icon-yii-alt", name: "Yii", color: '#EB6E2E' },
      { key: "icon-zend", icon: "icon-zend", name: "Zend", color: '#5DB200' },
      { key: "icon-doctrine", icon: "icon-doctrine", name: "Doctrine", color: '#FC6A31' },
      { key: "icon-graphql", icon: "icon-graphql", name: "GraphQL", color: '#E535AB' },
      { key: "icon-hibernate", icon: "icon-hibernate", name: "Hibernate", color: '#BCAE79' },
      { key: "icon-jpa", icon: "icon-jpa", name: "JPA", color: '#000000' },
      { key: "icon-mongoose", icon: "icon-mongoose", name: "Mongoose", color: '#850000' },
    ]
  },
  {
    id: 'devops',
    name: 'DevOps & Quality',
    icons: [
      { key: "icon-ansible", icon: "icon-ansible", name: "Ansible", color: '#1A1918' },
      { key: "icon-ansible-alt", icon: "icon-ansible-alt", name: "Ansible", color: '#1A1918' },
      { key: "icon-curl", icon: "icon-curl", name: "Curl", color: '#093754' },
      { key: "icon-gradle", icon: "icon-gradle", name: "Gradle", color: '#00D439' },
      { key: "icon-gradle-alt", icon: "icon-gradle-alt", name: "Gradle", color: '#00D439' },
      { key: "icon-grpc", icon: "icon-grpc", name: "grpc", color: '#244B5A' },
      { key: "icon-grpc-alt", icon: "icon-grpc-alt", name: "grpc", color: '#244B5A' },
      { key: "icon-grpc-alt2", icon: "icon-grpc-alt2", name: "grpc", color: '#244B5A' },
      { key: "icon-httpie", icon: "icon-httpie", name: "HTTPie", color: '#BD10E0' },
      { key: "icon-httpie-alt", icon: "icon-httpie-alt", name: "HTTPie", color: '#BD10E0' },
      { key: "icon-makefile", icon: "icon-makefile", name: "Makefile", color: '#323232' },
      { key: "icon-nomad", icon: "icon-nomad", name: "Nomad", color: '#00BC7F' },
      { key: "icon-rest", icon: "icon-rest", name: "Rest", color: null },
      { key: "icon-samba", icon: "icon-samba", name: "Samba", color: '#0000FF' },
      { key: "icon-samba-alt", icon: "icon-samba-alt", name: "Samba", color: '#0000FF' },
      { key: "icon-squid", icon: "icon-squid", name: "Squid", color: '#B8C5D9' },
      { key: "icon-systemd", icon: "icon-systemd", name: "Systemd", color: null },
      { key: "icon-apache-ant", icon: "icon-apache-ant", name: "Apache Ant", color: '#A81C7D' },
      { key: "icon-chef", icon: "icon-chef", name: "Chef", color: '#F08A20' },
      { key: "icon-cpanel", icon: "icon-cpanel", name: "cPanel", color: '#FF6C2C' },
      { key: "icon-cpanel-alt", icon: "icon-cpanel-alt", name: "cPanel", color: '#FF6C2C' },
      { key: "icon-datadog", icon: "icon-datadog", name: "Datadog", color: '#7846A5' },
      { key: "icon-datadog-alt", icon: "icon-datadog-alt", name: "Datadog", color: '#7846A5' },
      { key: "icon-directadmin", icon: "icon-directadmin", name: "Direct Admin", color: '#31B7E9' },
      { key: "icon-directadmin-alt", icon: "icon-directadmin-alt", name: "Direct Admin", color: '#31B7E9' },
      { key: "icon-dynatrace", icon: "icon-dynatrace", name: "Dynatrace", color: '#68BA00' },
      { key: "icon-ispconfig", icon: "icon-ispconfig", name: "ISP Config", color: '#C80000' },
      { key: "icon-ispconfig-alt", icon: "icon-ispconfig-alt", name: "ISP Config", color: '#C80000' },
      { key: "icon-jenkins", icon: "icon-jenkins", name: "Jenkins", color: '#D33833' },
      { key: "icon-jenkins-alt", icon: "icon-jenkins-alt", name: "Jenkins", color: '#D33833' },
      { key: "icon-kafka", icon: "icon-kafka", name: "Kafka", color: '#000000' },
      { key: "icon-kubernetes", icon: "icon-kubernetes", name: "Kubernetes", color: '#326CE5' },
      { key: "icon-loggly", icon: "icon-loggly", name: "Loggly", color: '#FF3A00' },
      { key: "icon-packer", icon: "icon-packer", name: "Packer", color: '#1DAEFF' },
      { key: "icon-plesk", icon: "icon-plesk", name: "Plesk", color: '#52BBE6' },
      { key: "icon-solarwinds", icon: "icon-solarwinds", name: "SolarWinds", color: '#F99D1C' },
      { key: "icon-sonar", icon: "icon-sonar", name: "Sonar", color: '#6AA9D4' },
      { key: "icon-sonar-alt", icon: "icon-sonar-alt", name: "Sonar", color: '#6AA9D4' },
      { key: "icon-sumologic", icon: "icon-sumologic", name: "Sumologic", color: '#000099' },
      { key: "icon-teamcity", icon: "icon-teamcity", name: "Teamcity", color: '#0FB4E8' },
      { key: "icon-teamcity-alt", icon: "icon-teamcity-alt", name: "Teamcity", color: '#0FB4E8' },
      { key: "icon-terraform", icon: "icon-terraform", name: "Terraform", color: '#5C4EE5' },
      { key: "icon-travis", icon: "icon-travis", name: "Travis", color: '#F3E85C' },
      { key: "icon-virtualmin", icon: "icon-virtualmin", name: "VirtualMin", color: '#182CCD' },
      { key: "icon-webmin", icon: "icon-webmin", name: "Webmin", color: '#759CD4' },
      { key: "icon-webmin-alt", icon: "icon-webmin-alt", name: "Webmin", color: '#759CD4' },
      { key: "icon-youtrack", icon: "icon-youtrack", name: "YouTrack", color: '#6D6CF4' },
      { key: "icon-youtrack-alt", icon: "icon-youtrack-alt", name: "YouTrack", color: '#6D6CF4' },
      { key: "icon-certbot", icon: "icon-certbot", name: "Certbot", color: '#ED1C24' },
      { key: "icon-powershell", icon: "icon-powershell", name: "Powershell", color: '#086FBF' },
      { key: "icon-ably", icon: "icon-ably", name: "Ably", color: '#ED760A' },
      { key: "icon-apache", icon: "icon-apache", name: "Apache", color: '#DC1148' },
      { key: "icon-jboss", icon: "icon-jboss", name: "JBoss", color: '#C60001' },
      { key: "icon-jboss-alt", icon: "icon-jboss-alt", name: "JBoss", color: '#C60001' },
      { key: "icon-jboss-tools", icon: "icon-jboss-tools", name: "JBoss Tools", color: '#C60001' },
      { key: "icon-lamp", icon: "icon-lamp", name: "Lamp", color: '#FF8F00' },
      { key: "icon-lets-encrypt", icon: "icon-lets-encrypt", name: "Let's Encrypt", color: '#003A70' },
      { key: "icon-linode", icon: "icon-linode", name: "Linode", color: '#00B259' },
      { key: "icon-mamp", icon: "icon-mamp", name: "Mamp", color: '#257CAF' },
      { key: "icon-mamp-alt", icon: "icon-mamp-alt", name: "Mamp", color: '#257CAF' },
      { key: "icon-nginx", icon: "icon-nginx", name: "NGinx", color: '#0E9749' },
      { key: "icon-nginx-alt", icon: "icon-nginx-alt", name: "NGinx", color: '#0E9749' },
      { key: "icon-puppet", icon: "icon-puppet", name: "Puppet", color: '#FBA832' },
      { key: "icon-sql-server", icon: "icon-sql-server", name: "SQL Server", color: '#D14646' },
      { key: "icon-tomcat", icon: "icon-tomcat", name: "Tomcat", color: '#D4A61B' },
      { key: "icon-tomcat-alt", icon: "icon-tomcat-alt", name: "Tomcat", color: '#D4A61B' },
      { key: "icon-wamp", icon: "icon-wamp", name: "Wamp", color: '#FF0099' },
      { key: "icon-wildfly", icon: "icon-wildfly", name: "Wildfly", color: '#001F37' },
      { key: "icon-xampp", icon: "icon-xampp", name: "Xampp", color: '#FB7A24' },
      { key: "icon-putty", icon: "icon-putty", name: "Putty", color: null },
      { key: "icon-puttygen", icon: "icon-puttygen", name: "PuttyGen", color: null },
    ]
  },
  {
    id: 'format',
    name: 'File Formats',
    icons: [
      { key: "icon-json", icon: "icon-json", name: "JSON", color: '#000000' },
      { key: "icon-markdown", icon: "icon-markdown", name: "Markdown", color: '#000000' },
      { key: "icon-markdown-alt", icon: "icon-markdown-alt", name: "Markdown", color: '#000000' },
      { key: "icon-mdx", icon: "icon-mdx", name: "MDX", color: '#F9AC00' },
      { key: "icon-yaml", icon: "icon-yaml", name: "YAML", color: '#F1901F' },
    ]
  },
  {
    id: 'ecomm',
    name: 'E-Commerce Solutions',
    icons: [
      { key: "icon-drupal", icon: "icon-drupal", name: "Drupal", color: '#0072C0' },
      { key: "icon-jigoshop", icon: "icon-jigoshop", name: "JigoShop", color: '#28BE72' },
      { key: "icon-joomla", icon: "icon-joomla", name: "Joomla", color: '#FC8F30' },
      { key: "icon-magento", icon: "icon-magento", name: "Magento", color: '#F26322' },
      { key: "icon-opencart", icon: "icon-opencart", name: "Opencart", color: '#00BAEC' },
      { key: "icon-opencart-alt", icon: "icon-opencart-alt", name: "Opencart", color: '#00BAEC' },
      { key: "icon-prestashop", icon: "icon-prestashop", name: "Prestashop", color: '#EA0074' },
      { key: "icon-shopify", icon: "icon-shopify", name: "Shopify", color: '#96BF47' },
      { key: "icon-shopware", icon: "icon-shopware", name: "Shopware", color: '#189EFF' },
      { key: "icon-woocommerce", icon: "icon-woocommerce", name: "WooCommerce", color: '#9B5C8F' },
      { key: "icon-woocommerce-alt", icon: "icon-woocommerce-alt", name: "WooCommerce", color: '#9B5C8F' },
      { key: "icon-wordpress", icon: "icon-wordpress", name: "WordPress", color: '#464646' },
    ]
  },
  {
    id: 'game',
    name: 'Game Engines & Softwares',
    icons: [
      { key: "icon-cryengine", icon: "icon-cryengine", name: "Cry Engine", color: '#000000' },
      { key: "icon-gamemaker", icon: "icon-gamemaker", name: "GameMaker", color: '#000000' },
      { key: "icon-neogfx", icon: "icon-neogfx", name: "Neogfx", color: '#A02727' },
      { key: "icon-ogre", icon: "icon-ogre", name: "Ogre", color: '#F3BA50' },
      { key: "icon-ogre-alt", icon: "icon-ogre-alt", name: "Ogre", color: '#F3BA50' },
      { key: "icon-opengl", icon: "icon-opengl", name: "OpenGL", color: '#4386B5' },
      { key: "icon-scratch", icon: "icon-scratch", name: "Scratch", color: '#EE9911' },
      { key: "icon-sdl", icon: "icon-sdl", name: "SDL", color: '#567084' },
      { key: "icon-sfml", icon: "icon-sfml", name: "SFML", color: '#8ECC3B' },
      { key: "icon-unity", icon: "icon-unity", name: "Unity", color: '#110B09' },
      { key: "icon-unreal", icon: "icon-unreal", name: "Unreal", color: '#000000' },
      { key: "icon-webgl", icon: "icon-webgl", name: "WebGL", color: '#961A1F' },
    ]
  },
  {
    id: 'erp',
    name: 'ERPs',
    icons: [
      { key: "icon-abas", icon: "icon-abas", name: "icon-Abas", color: '#1BBAA5' },
      { key: "icon-batchmaster", icon: "icon-batchmaster", name: "BatchMaster", color: '#0080C5' },
      { key: "icon-dynamics-ax", icon: "icon-dynamics-ax", name: "Dynamics AX", color: '#00188F' },
      { key: "icon-ifs", icon: "icon-ifs", name: "IFS", color: '#883E8F' },
      { key: "icon-odoo", icon: "icon-odoo", name: "Odoo", color: '#875A7B' },
      { key: "icon-pegasus", icon: "icon-pegasus", name: "Pegasus", color: '#E1B800' },
      { key: "icon-sage", icon: "icon-sage", name: "Sage", color: '#4DB848' },
      { key: "icon-sap", icon: "icon-sap", name: "SAP", color: '#0079C2' },
      { key: "icon-sap-alt", icon: "icon-sap-alt", name: "SAP", color: '#0079C2' },
      { key: "icon-syspro", icon: "icon-syspro", name: "SysPro", color: '#5BD4D4' },
    ]
  },
  {
    id: 'ai',
    name: 'AI, BI & Big Data',
    icons: [
      { key: "icon-arcsight", icon: "icon-arcsight", name: "Arcsight", color: '#C5211A' },
      { key: "icon-gluon", icon: "icon-gluon", name: "Gluon", color: '#428DD3' },
      { key: "icon-ibm-watson", icon: "icon-ibm-watson", name: "IBM Watson", color: '#26BEED' },
      { key: "icon-ibm-watson-alt", icon: "icon-ibm-watson-alt", name: "IBM Watson", color: '#26BEED' },
      { key: "icon-jupyter", icon: "icon-jupyter", name: "Jupyter", color: '#F37726' },
      { key: "icon-keras", icon: "icon-keras", name: "Keras", color: '#D00000' },
      { key: "icon-luminoth", icon: "icon-luminoth", name: "Luminoth", color: '#093C77' },
      { key: "icon-mapreduce", icon: "icon-mapreduce", name: "MapReduce", color: '#FDFF19' },
      { key: "icon-numpy", icon: "icon-numpy", name: "Numpy", color: '#FF9152' },
      { key: "icon-ocr", icon: "icon-ocr", name: "OCR", color: null },
      { key: "icon-qliksense", icon: "icon-qliksense", name: "Qlik Sense", color: '#63A330' },
      { key: "icon-qlikview", icon: "icon-qlikview", name: "Qlik View", color: '#63A330' },
      { key: "icon-sas", icon: "icon-sas", name: "SAS", color: '#0074BE' },
      { key: "icon-spark", icon: "icon-spark", name: "Spark", color: '#E25A1C' },
      { key: "icon-spark-alt", icon: "icon-spark-alt", name: "Spark", color: '#E25A1C' },
      { key: "icon-tableau", icon: "icon-tableau", name: "Tableau", color: '#002A70' },
      { key: "icon-tableau-alt", icon: "icon-tableau-alt", name: "Tableau", color: '#002A70' },
      { key: "icon-talend", icon: "icon-talend", name: "Talend", color: '#0675C1' },
      { key: "icon-talend-alt", icon: "icon-talend-alt", name: "Talend", color: '#0675C1' },
      { key: "icon-tensorflow", icon: "icon-tensorflow", name: "TensorFlow", color: '#F59122' },
    ]
  },
  {
    id: 'api',
    name: 'APIs',
    icons: [
      { key: "icon-coinbase", icon: "icon-coinbase", name: "Coinbase", color: '#0052CD' },
      { key: "icon-facebook-api", icon: "icon-facebook-api", name: "Facebook API", color: '#3C599B' },
      { key: "icon-openweather", icon: "icon-openweather", name: "OpenWeather", color: '#EA6E4B' },
      { key: "icon-paypal", icon: "icon-paypal", name: "Paypal", color: '#002F86' },
      { key: "icon-spotify", icon: "icon-spotify", name: "Spotify", color: '#1ED760' },
      { key: "icon-steam", icon: "icon-steam", name: "Steam", color: '#13376B' },
      { key: "icon-steam-alt", icon: "icon-steam-alt", name: "Steam", color: '#13376B' },
      { key: "icon-vault", icon: "icon-vault", name: "Vault", color: '#000000' },
      { key: "icon-mosquitto", icon: "icon-mosquitto", name: "Mosquitto", color: '#3C5280' },
      { key: "icon-rabbitmq", icon: "icon-rabbitmq", name: "RabbitMQ", color: '#FF6600' },
    ]
  }
];
